Repository ansible-collections/amazon.aws, pull requests merged in 2021-11, with the labels that each got.

#558 Add missing entry to AWS action group
  changelogs/fragments/557-action_group-missing-entry.yml
  meta/runtime.yml
Labels: bug, community_review, needs_triage, gate

#561 Fix for Issue #560 Add example for searching volumes by EC2 instance ID
  docs/amazon.aws.ec2_vol_info_module.rst
Labels: bug, new_contributor, community_review, needs_triage, docs, gate

#563 Fix docs issues.
  plugins/modules/ec2.py
  plugins/modules/ec2_vpc_endpoint_info.py
  plugins/modules/elb_classic_lb.py
Labels: gate

#567 minor changelog fixups prior to 2.1
  changelogs/changelog.yaml
  changelogs/fragments/551-ec2_ami-tag-on-create.yml
Labels: gate

#568 Move ec2_vol_info example from ec2_vol_info_module.rst to ec2_vol_info.py
  plugins/modules/ec2_vol_info.py
Labels: gate

#565 Prep 2.1.0 release
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/377-ec2_elb_lb-boto3.yml
  changelogs/fragments/430-add_support_for_ipv6_addresses.yml
  changelogs/fragments/507-fix_cloudformation_changeset_detection.yml
  changelogs/fragments/508-s3_bucket-digital_ocean.yml
  changelogs/fragments/509-ec2_vol_add_check_mode_support.yml
  changelogs/fragments/512-ec2_snapshot_add_check_mode_support.yml.yml
  changelogs/fragments/516-ec2_ami_add_check_mode_support.yml
  changelogs/fragments/520-ec2_ami-tagging.yml
  changelogs/fragments/522-ec2_eni-tagging.yml
  changelogs/fragments/523-ec2_vpc_igw-tagging.yml
  changelogs/fragments/524-ec2_vpc_nat_gateway-tagging.yml
  changelogs/fragments/525-ec2_vpc_endpoint-tagging.yml
  changelogs/fragments/526-ec2_instance_search_tags.yml
  changelogs/fragments/527-ec2_instance-tagging.yml
  changelogs/fragments/531-use_tags_handlers.yml
  changelogs/fragments/534-ec2_eni_add_check_mode_support.yml
  changelogs/fragments/544-vpc-endpoint-add-subnets-sg-option.yml
  changelogs/fragments/548-ec2_key-tagging.yml
  changelogs/fragments/551-ec2_ami-tag-on-create.yml
  changelogs/fragments/552-elb_classic_lb-fact.yml
  changelogs/fragments/557-action_group-missing-entry.yml
  docs/amazon.aws.aws_s3_module.rst
  docs/amazon.aws.aws_service_ip_ranges_lookup.rst
  docs/amazon.aws.ec2_elb_lb_module.rst
  docs/amazon.aws.ec2_eni_info_module.rst
  docs/amazon.aws.ec2_key_module.rst
  docs/amazon.aws.ec2_module.rst
  docs/amazon.aws.ec2_vol_info_module.rst
  docs/amazon.aws.ec2_vol_module.rst
  docs/amazon.aws.ec2_vpc_endpoint_info_module.rst
  docs/amazon.aws.ec2_vpc_endpoint_module.rst
  docs/amazon.aws.elb_classic_lb_module.rst
  galaxy.yml
Labels: gate

#569 Add wildcard to credentials file in .gitignore
  tests/.gitignore
Labels: gate

#571 Docs s3_bucket
  plugins/modules/s3_bucket.py
Labels: gate

#577 Add patchback configs
  .github/patchback.yml
Labels: gate

#575 [3.0.0] Add deprecation notice for boto support.
  README.md
  changelogs/fragments/575-deprecate-boto.yml
Labels: gate

#574 [3.0.0] Bump minimal botocore version to 1.19.0
  README.md
  changelogs/fragments/574-botocore-1-19-0.yml
  plugins/doc_fragments/aws.py
  plugins/lookup/aws_account_attribute.py
  plugins/lookup/aws_secret.py
  plugins/lookup/aws_ssm.py
  plugins/module_utils/core.py
  plugins/modules/s3_bucket.py
  requirements.txt
  tests/integration/constraints.txt
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/ownership_controls.yml
  tests/integration/targets/setup_botocore_pip/defaults/main.yml
  tests/unit/constraints.txt
  tests/unit/module_utils/core/ansible_aws_module/test_minimal_versions.py
Labels: gate

#539 ec2_instance: Add count parameter to ec2_instance
  changelogs/fragments/539-ec2_instance_add_count_param.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance/inventory
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/instance_multiple.yml
Labels: feature, integration, module, tests, community_review, plugins, gate

#581 Add missing version_added to ec2_instance.py
  plugins/modules/ec2_instance.py
Labels: gate
