Repository ansible-collections/amazon.aws, pull requests merged in 2021-05, with the labels that each got.

#347 Remove shippable references from repo
  README.md
  shippable.yml
  tests/integration/targets/aws_az_info/aliases
  tests/integration/targets/aws_caller_info/aliases
  tests/integration/targets/aws_s3/aliases
  tests/integration/targets/cloudformation/aliases
  tests/integration/targets/ec2/aliases
  tests/integration/targets/ec2_ami/aliases
  tests/integration/targets/ec2_elb_lb/aliases
  tests/integration/targets/ec2_eni/aliases
  tests/integration/targets/ec2_group/aliases
  tests/integration/targets/ec2_key/aliases
  tests/integration/targets/ec2_metadata_facts/aliases
  tests/integration/targets/ec2_snapshot/aliases
  tests/integration/targets/ec2_tag/aliases
  tests/integration/targets/ec2_vol/aliases
  tests/integration/targets/ec2_vpc_dhcp_option/aliases
  tests/integration/targets/ec2_vpc_net/aliases
  tests/integration/targets/ec2_vpc_subnet/aliases
  tests/integration/targets/inventory_aws_ec2/aliases
  tests/integration/targets/lookup_aws_account_attribute/aliases
  tests/integration/targets/module_utils_core/aliases
  tests/integration/targets/module_utils_ec2/aliases
  tests/integration/targets/module_utils_waiter/aliases
  tests/integration/targets/s3_bucket/aliases
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
  tests/utils/shippable/aws.sh
  tests/utils/shippable/check_matrix.py
  tests/utils/shippable/sanity.sh
  tests/utils/shippable/shippable.sh
  tests/utils/shippable/timing.py
  tests/utils/shippable/timing.sh
  tests/utils/shippable/units.sh
Labels: bug, community_review, gate, integration, needs_triage, plugins, tests

#350 Add route53 waiter with throttling retries
  changelogs/fragments/350-route53-waiter.yml
  plugins/module_utils/waiters.py
Labels: gate

#311 add object ownership controls options for s3 bucket
  changelogs/fragments/311-s3_bucket-allow-object-ownership-configuration.yaml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/ownership_controls.yml
Labels: community_review, feature, gate, integration, module, plugins, tests

#341 s3: raise an error if the bucket name is not correct
  plugins/module_utils/s3.py
  plugins/modules/aws_s3.py
  plugins/modules/s3_bucket.py
  tests/integration/targets/aws_s3/tasks/main.yml
  tests/unit/module_utils/test_s3.py
Labels: gate, integration, module, module_utils, needs_info, needs_template, plugins, tests

#352 Correct changelog data from 1.4.1
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: gate

#356 ec2_snapshot - boto3 migration
  changelogs/fragments/356-ec2_snapshot-boto3-migration.yml
  plugins/module_utils/waiters.py
  plugins/modules/ec2_snapshot.py
  tests/integration/targets/ec2_snapshot/tasks/main.yml
Labels: gate

#360 Add netcommon to test requirements for ipv6 filter
  tests/requirements.yml
Labels: gate

#318 Add permission to upload ACL in ExtraArgs
  changelogs/fragments/318-s3-upload-acl.yml
  plugins/modules/aws_s3.py
  tests/integration/targets/aws_s3/defaults/main.yml
  tests/integration/targets/aws_s3/tasks/main.yml
  tests/integration/targets/aws_s3/templates/policy.json.j2
Labels: community_review, docs, gate, integration, module, new_contributor, plugins, tests

#354 Migrate ec2 instance modules
  changelogs/fragments/migrate_ec2_instance.yml
  meta/runtime.yml
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_instance_facts.py
  plugins/modules/ec2_instance_info.py
  tests/integration/targets/ec2_instance/aliases
  tests/integration/targets/ec2_instance/roles/ec2_instance/defaults/main.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/iam_instance_role.yml
  tests/integration/targets/ec2_instance/roles/ec2_instance/tasks/main.yml
  tests/sanity/ignore-2.9.txt
Labels: gate

#297 scrub_none_parameters - set default for descend_into_lists to True (breaking change)
  changelogs/fragments/297-scrub_none_parameters-descend-default.yml
  plugins/module_utils/core.py
  tests/unit/module_utils/core/test_scrub_none_parameters.py
Labels: community_review, feature, gate, module_utils, plugins, small_patch, tests

#290 Core parameter sanity test cleanup (breaking change)
  changelogs/fragments/290-lint-cleanup.yml
  plugins/module_utils/core.py
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
Labels: bug, community_review, gate, module_utils, plugins, tests

#298 Update the default module requirements from python-2.6/boto to python-3.6/botocore-1.16 (breaking change)
  changelogs/fragments/298-python3.6.yml
  plugins/doc_fragments/aws.py
  plugins/lookup/aws_account_attribute.py
  plugins/lookup/aws_secret.py
  plugins/lookup/aws_ssm.py
  plugins/modules/aws_az_info.py
  plugins/modules/aws_caller_info.py
  plugins/modules/aws_s3.py
  plugins/modules/cloudformation.py
  plugins/modules/cloudformation_info.py
  plugins/modules/ec2.py
  plugins/modules/ec2_ami_info.py
  plugins/modules/ec2_elb_lb.py
  plugins/modules/ec2_eni_info.py
  plugins/modules/ec2_group.py
  plugins/modules/ec2_group_info.py
  plugins/modules/ec2_key.py
  plugins/modules/ec2_snapshot_info.py
  plugins/modules/ec2_tag.py
  plugins/modules/ec2_tag_info.py
  plugins/modules/ec2_vol_info.py
  plugins/modules/ec2_vpc_dhcp_option.py
  plugins/modules/ec2_vpc_dhcp_option_info.py
  plugins/modules/ec2_vpc_net.py
  plugins/modules/ec2_vpc_net_info.py
  plugins/modules/ec2_vpc_subnet.py
  plugins/modules/ec2_vpc_subnet_info.py
  plugins/modules/s3_bucket.py
  requirements.txt
  tests/unit/requirements.txt
Labels: community_review, docs, gate, lookup, module, plugins

#361 drop support of community.general for integration testing
  changelogs/fragments/361-drop-community.general-support-for-integration.tests.yml
  tests/integration/targets/ec2_eni/tasks/test_deletion.yaml
  tests/integration/targets/ec2_eni/tasks/test_eni_basic_creation.yaml
  tests/integration/targets/ec2_eni/tasks/test_ipaddress_assign.yaml
  tests/integration/targets/ec2_eni/tasks/test_modifying_delete_on_termination.yaml
  tests/integration/targets/ec2_snapshot/tasks/main.yml
  tests/integration/targets/ec2_vpc_dhcp_option/tasks/main.yml
  tests/integration/targets/ec2_vpc_net/tasks/main.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/populate_cache.yml
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_constructed.yml.j2
  tests/integration/targets/inventory_aws_rds/templates/inventory_with_constructed.j2
  tests/requirements.yml
Labels: gate

#355 Cloudformation: use is_boto3_error_message
  plugins/modules/cloudformation.py
  tests/unit/plugins/modules/test_cloudformation.py
Labels: gate

#358 cloudformation - use standard retry decorator pattern
  plugins/modules/cloudformation.py
Labels: gate

#369 Update README with new python and botocore requirements
  README.md
Labels: gate
