Repository ansible-collections/amazon.aws, pull requests merged in 2022-01, with the labels that each got.

#590 Fix tempfolder path since Fedora uses tmpfs
  tests/integration/targets/aws_s3/tasks/main.yml
Labels: gate

#603 aws_s3 - fix issue when copy missing key from bucket
  changelogs/fragments/593-aws_s3-fix-copy-when-missing-key.yml
  plugins/modules/aws_s3.py
  tests/integration/targets/aws_s3/tasks/copy_object.yml
Labels: gate

#604 Tag EC2 volume on creation
  changelogs/fragments/603-ec2_vol-add-tags-on-creation.yml
  plugins/modules/ec2_vol.py
Labels: gate

#606 ec2_vol: set iops even if unchanged for boto req
  changelogs/fragments/606-ec2_vol-set-iops-even-if-unchanged-for-boto-req.yml
  plugins/modules/ec2_vol.py
Labels: gate, backport-2

#599 Prepare for distutils.version being removed in Python 3.12
  changelogs/fragments/disutils.version.yml
  plugins/module_utils/_version.py
  plugins/module_utils/core.py
  plugins/module_utils/version.py
  plugins/modules/ec2.py
Labels: gate

#595 aws_s3: Add latest choice on overwrite parameter
  changelogs/fragments/595-aws_s3-add-latest-choice-on-overwrite-parameter.yml
  plugins/modules/aws_s3.py
  tests/integration/targets/aws_s3/tasks/main.yml
Labels: gate

#616 ec2_key - support for ED25519 key type
  changelogs/fragments/614-ec2_key-add-support-for-ed25519-key-type.yml
  plugins/modules/ec2_key.py
  tests/integration/targets/ec2_key/meta/main.yml
  tests/integration/targets/ec2_key/tasks/main.yml
Labels: gate

#621 Add option to prefix and/or suffix hostvar coming from AWS
  changelogs/fragments/619-aws_ec2-aws_rds-add-support-for-hostvars_prefix-and-hostvars_suffix.yml
  plugins/inventory/aws_ec2.py
  plugins/inventory/aws_rds.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/inventory_aws_ec2/runme.sh
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_hostvars_prefix_suffix.yml.j2
  tests/integration/targets/inventory_aws_rds/playbooks/test_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/inventory_aws_rds/runme.sh
  tests/integration/targets/inventory_aws_rds/templates/inventory_with_hostvars_prefix_suffix.j2
Labels: gate

#613 ec2_vpc_endpoint: improve documentation to provide details about route_table_ids
  plugins/modules/ec2_vpc_endpoint.py
Labels: gate

#632 Disable broken integration test - lookup_aws_account_attribute
  tests/integration/targets/lookup_aws_account_attribute/aliases
Labels: gate

#597 ec2_vol: Add support for OutpostArn param
  changelogs/fragments/597-ec2_vol-add-outpostarn-support.yml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_vol.py
  tests/unit/module_utils/test_ec2.py
Labels: gate

#587 ec2_instance: Fix launch template condition, handle launch template - default value for instance_type
  changelogs/fragments/587-ec2_instance-default-instance-type-launch-template.yml
  plugins/modules/ec2_instance.py
  tests/sanity/ignore-2.9.txt
Labels: gate

#627 `ec2_vol` - support changing from volume without IOPS to one with IOPS
  changelogs/fragments/626-ec2_vol-iops-when-source-does-not-have-iops.yml
  plugins/modules/ec2_vol.py
  tests/integration/targets/ec2_vol/tasks/main.yml
Labels: gate, backport-2

#598 ec2_vpc_subnet: Add support for OutpostArn param
  changelogs/fragments/598-ec2_vpc_subnet-add-outpostarn-support.yml
  plugins/modules/ec2_vpc_subnet.py
Labels: gate

#619 Move iam profile regexes logic to module_utils
  plugins/module_utils/core.py
  plugins/module_utils/iam.py
  plugins/modules/ec2_instance.py
  tests/unit/module_utils/core/test_parse_aws_arn.py
Labels: gate

#642 Move AWSRetry out of module_utils.ec2
  plugins/module_utils/ec2.py
  plugins/module_utils/retries.py
  tests/unit/module_utils/test_retries.py
Labels: new_plugin, feature, module_utils, tests, community_review, needs_triage, plugins, gate, mergeit, do_not_backport

#639 Bump release to 4.0.0-dev0
  galaxy.yml
Labels: feature, has_issue, community_review, needs_triage, small_patch, mergeit, do_not_backport

#630 [Breaking Change] Remove support for old boto SDK (not boto3/botocore)
  CONTRIBUTING.md
  README.md
  changelogs/fragments/630-remove-boto.yml
  plugins/doc_fragments/aws.py
  plugins/module_utils/ec2.py
  plugins/modules/ec2.py
  requirements.txt
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/targets/ec2/aliases
  tests/integration/targets/ec2/defaults/main.yml
  tests/integration/targets/ec2/meta/main.yml
  tests/integration/targets/ec2/tasks/main.yml
  tests/integration/targets/ec2_instance/main.yml
  tests/integration/targets/module_utils_ec2/aliases
  tests/integration/targets/module_utils_ec2/connect_to_aws.yml
  tests/integration/targets/module_utils_ec2/ec2_connect.yml
  tests/integration/targets/module_utils_ec2/inventory
  tests/integration/targets/module_utils_ec2/meta/main.yml
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/files/amazonroot.pem
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/files/isrg-x1.pem
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/library/example_module.py
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/meta/main.yml
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/credentials.yml
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/endpoints.yml
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/main.yml
  tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/profiles.yml
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/files/amazonroot.pem
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/files/isrg-x1.pem
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/library/example_module.py
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/meta/main.yml
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/tasks/credentials.yml
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/tasks/endpoints.yml
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/tasks/main.yml
  tests/integration/targets/module_utils_ec2/roles/ec2_connect/tasks/profiles.yml
  tests/integration/targets/module_utils_ec2/runme.sh
  tests/integration/targets/module_utils_ec2/setup.yml
  tests/integration/targets/module_utils_ec2/templates/boto_config.j2
  tests/integration/targets/module_utils_ec2/templates/session_credentials.yml.j2
  tests/sanity/ignore-2.9.txt
  tests/unit/requirements.txt
Labels: feature, has_issue, integration, module, module_utils, tests, community_review, plugins, mergeit, do_not_backport
