Repository ansible-collections/amazon.aws, pull requests merged in 2023-04, with the labels that each got.

#1436 Add backup_vault and backup_vault_info module to amazon.aws
  meta/runtime.yml
  plugins/modules/backup_vault.py
  plugins/modules/backup_vault_info.py
  tests/integration/targets/backup_tag/aliases
  tests/integration/targets/backup_tag/tasks/main.yml
  tests/integration/targets/backup_vault/aliases
  tests/integration/targets/backup_vault/defaults/main.yml
  tests/integration/targets/backup_vault/meta/main.yml
  tests/integration/targets/backup_vault/tasks/main.yml
  tests/integration/targets/backup_vault/vars/main.yml
Labels: new_plugin, new_module, integration, module, tests, community_review, plugins, mergeit

#1454 add ansible bot to label issue/pull requests using github action
  .github/workflows/ansible-bot.yml
Labels: mergeit

#1455 DNM - trigger for bot labeler
  .github/workflows/ansible-bot.yml
Labels: mergeit

#1456 DNM - trigger for bot labeler
  .github/workflows/ansible-bot.yml
Labels: mergeit

#1457 lambda_info: remove unnecessary snake_casing of env_vars when querying lambda config
  changelogs/fragments/1457-lambda_info-fix-env-var-in-output.yml
  plugins/modules/lambda_info.py
Labels: mergeit

#1462 Minor Sanity test fixes
  changelogs/fragments/1462-sanity.yml
  plugins/modules/backup_tag_info.py
  plugins/modules/backup_vault.py
  plugins/modules/route53_info.py
  test-requirements.txt
  tests/integration/targets/cloudtrail/main.yml
  tests/integration/targets/ec2_vpc_endpoint_service_info/defaults/main.yml
  tests/integration/targets/ec2_vpc_endpoint_service_info/tasks/main.yml
  tests/integration/targets/inventory_aws_ec2/tasks/setup.yml
  tests/integration/targets/inventory_aws_ec2/tasks/tear_down.yml
  tests/integration/targets/inventory_aws_ec2/tasks/test_refresh_inventory.yml
  tests/sanity/ignore-2.16.txt
  tests/unit/plugins/modules/test_backup_restore_job_info.py
Labels: mergeit

#1393 Add github action for sanity and unit tests
  .github/workflows/tests.yml
  changelogs/fragments/add_github_actions_unitandsanity.yml
Labels: feature, integration, tests, community_review, mergeit

#1472 Update README.md and meta/runtime.yml to reflect our ansible core testing versions
  README.md
  changelogs/fragments/20230423-update_readme_and_runtime.yml
  meta/runtime.yml
Labels: mergeit

#1468 Pick up app_callback -> set_password rather than app_callback -> set_passwd
  changelogs/fragments/20230424-ec2_instance-app_callback.yml
  plugins/modules/ec2_instance.py
Labels: mergeit

#1481 [manual backport stable-5] Drop tests for ancient botocore (not supported) (#1477)
  changelogs/fragments/1477-elbv2-botocore.yml
  plugins/module_utils/elbv2.py
Labels: mergeit

#1480 [manual backport stable-5] Don't consider prop 'StateTransitionedTimestamp' in change detection (#1440)
  changelogs/fragments/1440-cloudwatch_metric_alarm-fix-change-detection.yml
  plugins/modules/cloudwatch_metric_alarm.py
Labels: mergeit

#1479 [manual backport stable-5] lambda_info: remove unnecessary snake_casing of env_vars when querying lambda config (#1457)
  changelogs/fragments/1457-lambda_info-fix-env-var-in-output.yml
  plugins/modules/lambda_info.py
Labels: mergeit

#1490 [manual backport stable-5] lambda_event: Add support for FunctionResponseTypes (#1209)
  changelogs/fragments/1209-lambda_event-add-support-for-function_response_types.yml
  plugins/modules/lambda_event.py
  tests/integration/targets/lambda_event/aliases
  tests/integration/targets/lambda_event/defaults/main.yml
  tests/integration/targets/lambda_event/files/mini_lambda.py
  tests/integration/targets/lambda_event/files/minimal_trust_policy.json
  tests/integration/targets/lambda_event/meta/main.yml
  tests/integration/targets/lambda_event/tasks/main.yml
  tests/integration/targets/lambda_event/tasks/setup.yml
  tests/integration/targets/lambda_event/tasks/teardown.yml
Labels: mergeit

#1489 [manual backport stable-5] kms_key: Add multi region support to create_key (#1290)
  changelogs/fragments/1290-create_multi_region_key.yml
  plugins/modules/kms_key.py
  tests/integration/targets/kms_key/inventory
  tests/integration/targets/kms_key/roles/aws_kms/tasks/test_multi_region.yml
  tests/integration/targets/kms_key/roles/aws_kms/tasks/test_states.yml
  tests/unit/plugins/modules/test_kms_key.py
Labels: mergeit

#1487 [manual backport stable-5] ec2_ami: Add support for params BootMode, TpmSupport, UefiData (#1037)
  changelogs/fragments/1037-ec2_ami-add-support-for-boot_mode-tpm_support-uefi_data.yml
  plugins/modules/ec2_ami.py
  tests/integration/targets/ec2_ami/meta/main.yml
  tests/integration/targets/ec2_ami/tasks/main.yml
  tests/unit/plugins/modules/test_ec2_ami.py
Labels: mergeit

#1486 [manual backport stable-5] ec2_vpc_nat_gateway: Add support for connectivity_type = private (#1267)
  changelogs/fragments/1267-ec2_vpc_nat_gateway_connectivitytype.yml
  plugins/modules/ec2_vpc_nat_gateway.py
  tests/integration/targets/ec2_vpc_nat_gateway/tasks/main.yml
Labels: mergeit

#1485 [manual backport stable-5] Add metrics and extended_statistic keys to cloudwatch module (#1133)
  changelogs/fragments/1133-add_metrics_cloudwatch.yml
  plugins/modules/cloudwatch_metric_alarm.py
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
Labels: mergeit
