Repository ansible-collections/amazon.aws, pull requests merged in 2023-11, with the labels that each got.

#1840 Prep amazon.aws 7.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1538-s3-null.yml
  changelogs/fragments/1548-s3_object-leading-slash.yml
  changelogs/fragments/1551-ec2_inventory-no-region.yml
  changelogs/fragments/1587-LooseVersion.yml
  changelogs/fragments/1607-NoSuchTagSet.yml
  changelogs/fragments/1631-route53_health_check-added-calculcated.yml
  changelogs/fragments/1647-add-type-started-and-stopped.yml
  changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
  changelogs/fragments/1683-route53-wait_id.yml
  changelogs/fragments/1705-rds_cluster-add-support-remove-cluster-from-global-db.yml
  changelogs/fragments/1771-isort.yml
  changelogs/fragments/1778-elb_application_lb_info-fetch-subsets.yml
  changelogs/fragments/1799-s3_object-bucket.yml
  changelogs/fragments/1802-flynt.yml
  changelogs/fragments/1825-ec2_instances.yml
  changelogs/fragments/20230612-s3_object-support-copy-objects-recursively.yml
  changelogs/fragments/20230702-isort.yml
  changelogs/fragments/20231020-iam_server_certificate-revert.yml
  changelogs/fragments/7.0.0-urls.yml
  changelogs/fragments/add-pytest-ansible.yml
  changelogs/fragments/ansible_version_update.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/ec2_instance_info-support-new-attribute.yml
  changelogs/fragments/ec2_vpc_igw-delete_unattached-gateway.yml
  changelogs/fragments/ec2_vpc_route_table_info-filter-fix.yml
  changelogs/fragments/migrate_aws_region_info.yml
  changelogs/fragments/migrate_iam_access_key.yml
  changelogs/fragments/migrate_iam_group.yml
  changelogs/fragments/migrate_iam_managed_policy.yml
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  changelogs/fragments/migrate_iam_password_policy.yml
  changelogs/fragments/migrate_iam_role.yml
  changelogs/fragments/migrate_s3_bucket_info.yml
  changelogs/fragments/migrate_sts_assume_role.yml
  changelogs/fragments/python37.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: skip-changelog

#1837 Bump version from 7.0.0 to 8.0.0-dev0
  changelogs/fragments/8.0.0-dev0.yml
  galaxy.yml
  plugins/module_utils/common.py
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
Labels: mergeit

#1847 s3_object: fix value typo from last to latest
  changelogs/fragments/1847-s3_object-fix-false-deprecation-warning.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-6, backport-7

#1844 Tag security groups on create
  changelogs/fragments/1843-ec2_security_group-tags.yml
  plugins/modules/ec2_security_group.py
  tests/integration/targets/ec2_security_group/tasks/group_info.yml
Labels: mergeit, backport-7

#1849 Update main changelog to reflect 7.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1538-s3-null.yml
  changelogs/fragments/1548-s3_object-leading-slash.yml
  changelogs/fragments/1551-ec2_inventory-no-region.yml
  changelogs/fragments/1587-LooseVersion.yml
  changelogs/fragments/1607-NoSuchTagSet.yml
  changelogs/fragments/1631-route53_health_check-added-calculcated.yml
  changelogs/fragments/1647-add-type-started-and-stopped.yml
  changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
  changelogs/fragments/1683-route53-wait_id.yml
  changelogs/fragments/1705-rds_cluster-add-support-remove-cluster-from-global-db.yml
  changelogs/fragments/1771-isort.yml
  changelogs/fragments/1778-elb_application_lb_info-fetch-subsets.yml
  changelogs/fragments/1799-s3_object-bucket.yml
  changelogs/fragments/1802-flynt.yml
  changelogs/fragments/1825-ec2_instances.yml
  changelogs/fragments/20230612-s3_object-support-copy-objects-recursively.yml
  changelogs/fragments/20230702-isort.yml
  changelogs/fragments/20231020-iam_server_certificate-revert.yml
  changelogs/fragments/7.0.0-urls.yml
  changelogs/fragments/add-pytest-ansible.yml
  changelogs/fragments/ansible_version_update.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/ec2_instance_info-support-new-attribute.yml
  changelogs/fragments/ec2_vpc_igw-delete_unattached-gateway.yml
  changelogs/fragments/ec2_vpc_route_table_info-filter-fix.yml
  changelogs/fragments/migrate_aws_region_info.yml
  changelogs/fragments/migrate_iam_access_key.yml
  changelogs/fragments/migrate_iam_group.yml
  changelogs/fragments/migrate_iam_managed_policy.yml
  changelogs/fragments/migrate_iam_mfa_device_info.yml
  changelogs/fragments/migrate_iam_password_policy.yml
  changelogs/fragments/migrate_iam_role.yml
  changelogs/fragments/migrate_s3_bucket_info.yml
  changelogs/fragments/migrate_sts_assume_role.yml
  changelogs/fragments/python37.yml
Labels: mergeit, skip-changelog

#1845 Work on ec2_instance integration test flakes
  tests/integration/targets/ec2_instance_block_devices/defaults/main.yml
  tests/integration/targets/ec2_instance_block_devices/meta/main.yml
  tests/integration/targets/ec2_instance_block_devices/tasks/main.yml
  tests/integration/targets/ec2_instance_state_config_updates/defaults/main.yml
  tests/integration/targets/ec2_instance_state_config_updates/meta/main.yml
  tests/integration/targets/ec2_instance_state_config_updates/tasks/main.yml
  tests/integration/targets/setup_ec2_instance_env/tasks/main.yml
Labels: mergeit, backport-6, skip-changelog, backport-7

#1848 Work on ec2_vpc_subnet related test flake
  changelogs/fragments/1848-ec2_vpc_subnet-wait-creation.yml
  plugins/modules/ec2_vpc_subnet.py
Labels: mergeit, backport-6, backport-7

#1873 (test flake) ec2_vpc_dhcp_option - wait for deletion to complete
  tests/integration/targets/ec2_vpc_dhcp_option/tasks/main.yml
Labels: mergeit, backport-6, skip-changelog, backport-7

#1829 is_boto3_error_code - support sets and tuples
  changelogs/fragments/1829-is_boto3_error-tuple.yml
  plugins/module_utils/botocore.py
  tests/unit/module_utils/botocore/test_is_boto3_error_code.py
Labels: mergeit

#1828 ec2_instance - Support AdditionalInfo option.
  changelogs/fragments/1828-ec2_instance_additional_info.yml
  plugins/modules/ec2_instance.py
Labels: mergeit

#1876 Use TagSpecifications parameter when creating EC2 resources
  changelogs/fragments/1843-ec2_eip.yml
  changelogs/fragments/1843-ec2_vpc_igw.yml
  changelogs/fragments/1843-ec2_vpc_route_table.yml
  changelogs/fragments/1843-ec2_vpc_subnet.yml
  plugins/module_utils/tagging.py
  plugins/modules/ec2_eip.py
  plugins/modules/ec2_vpc_igw.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_subnet.py
  tests/integration/targets/ec2_eip/tasks/main.yml
  tests/integration/targets/ec2_vpc_igw/tasks/main.yml
  tests/integration/targets/ec2_vpc_route_table/tasks/main.yml
  tests/integration/targets/ec2_vpc_subnet/tasks/main.yml
  tests/unit/module_utils/test_tagging.py
Labels: mergeit, backport-7

#1882 allow s3_object put to specify metadata again
  changelogs/fragments/1881-allow-s3_object-to-specify-content-type-in-metadata.yml
  plugins/modules/s3_object.py
  tests/integration/targets/s3_object/tasks/main.yml
Labels: mergeit, backport-6, backport-7
