Repository ansible-collections/amazon.aws, pull requests merged in 2023-06, with the labels that each got.

#1582 aws_ec2 inventory : Modify accepted type for hostnames argument in the module doc
  changelogs/fragments/ec2-inventory-hostnames-doc.yml
  plugins/inventory/aws_ec2.py
Labels: mergeit, backport-5, backport-6

#1588 [manual backport stable-5] Fix: ec2_instance idempotency issue when attaching ENI to isntance (#1576)
  changelogs/fragments/ec2_instance-eni-attach-idempotency.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_external_resource_attach/tasks/main.yml
Labels: mergeit

#1593 autoscaling_group_info - Fix ValidationError when describing ASGs that have more than 20 Load Balancer Target Groups attached
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  tests/integration/targets/autoscaling_group/roles/ec2_asg/tasks/create_update_delete.yml
Labels: mergeit, backport-5, backport-6

#1570 ACMServiceManager.list_certificates_with_backoff: explicit key type filter added
  changelogs/fragments/1567-list-certificate-all-key-types.yml
  plugins/module_utils/acm.py
Labels: mergeit, backport-6

#1598 [manual backport stable-6] autoscaling_group_info - Fix ValidationError when describing ASGs tha…
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  tests/integration/targets/autoscaling_group/roles/ec2_asg/tasks/create_update_delete.yml
Labels: mergeit, backport-5

#1600 [manual backport stable-5] autoscaling_group_info - Fix ValidationError when describing ASGs tha…
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  tests/integration/targets/autoscaling_group/roles/ec2_asg/tasks/create_update_delete.yml
Labels: mergeit

#1599 austoscaling_group* - Fix sanity errors
  changelogs/fragments/20230506-autoscaling_group-fix_sanity.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
Labels: mergeit

#1601 Prep amazon.aws 6.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1459-rds_instance-add-support-for-ca_certificate_identifier-to-create-update-instance.yml
  changelogs/fragments/1464-ec2_snapshot-ec2_snapshot_info-support-modifying-create-volume-permissions.yml
  changelogs/fragments/1510-elb_application_lb-fix-alb-specific-attributes-not-added-on-create.yml
  changelogs/fragments/1548-s3_object-leading-slash-deprecate.yml
  changelogs/fragments/1567-list-certificate-all-key-types.yml
  changelogs/fragments/1578-rds-instance-docs.yml
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  changelogs/fragments/20230526-ec2_mertadata_facts-handle_compressed_user_data.yml
  changelogs/fragments/20230531-aws_ec2-use_ssm_inventory_documentation.yml
  changelogs/fragments/ec2-inventory-hostnames-doc.yml
  changelogs/fragments/ec2_instance-eni-attach-idempotency.yml
  changelogs/fragments/test-reqs.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit

#1603 Prep amazon.aws 5.5.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1510-elb_application_lb-fix-alb-specific-attributes-not-added-on-create.yml
  changelogs/fragments/1528-lookup-error.yml
  changelogs/fragments/1578-rds-instance-docs.yml
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  changelogs/fragments/ec2_instance-eni-attach-idempotency.yml
  changelogs/fragments/endpoint.yml
  changelogs/fragments/test-reqs.yml
  galaxy.yml
Labels: mergeit

#1605 Update main branch after release 6.1.0 and 6.0.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1459-rds_instance-add-support-for-ca_certificate_identifier-to-create-update-instance.yml
  changelogs/fragments/1464-ec2_snapshot-ec2_snapshot_info-support-modifying-create-volume-permissions.yml
  changelogs/fragments/1510-elb_application_lb-fix-alb-specific-attributes-not-added-on-create.yml
  changelogs/fragments/1548-s3_object-leading-slash-deprecate.yml
  changelogs/fragments/1567-list-certificate-all-key-types.yml
  changelogs/fragments/1578-rds-instance-docs.yml
  changelogs/fragments/1593-autoscaling_group_info-20-target-groups-per-call.yml
  changelogs/fragments/20230526-ec2_mertadata_facts-handle_compressed_user_data.yml
  changelogs/fragments/20230531-aws_ec2-use_ssm_inventory_documentation.yml
  changelogs/fragments/ec2-inventory-hostnames-doc.yml
  changelogs/fragments/ec2_instance-eni-attach-idempotency.yml
  changelogs/fragments/test-reqs.yml
Labels: mergeit

#1611 Backup plan params bugfix
  changelogs/fragments/202306012-backup_plan-remove-none-from-nested-params.yml
  plugins/modules/backup_plan.py
  tests/integration/targets/backup_plan/tasks/main.yml
Labels: mergeit, backport-6

#1621 [manual backport stable-6] Fix sanity (#1599)
  changelogs/fragments/20230506-autoscaling_group-fix_sanity.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
Labels: mergeit

#1617 Fix typo in rds_instance docs for master_user_password
  plugins/modules/rds_instance.py
Labels: mergeit, backport-5, backport-6

#1610 Backup vault tag bugfix
  changelogs/fragments/20230612-backup_vault-fix-tag-update.yml
  plugins/modules/backup_vault.py
  tests/integration/targets/backup_vault/tasks/main.yml
Labels: mergeit, backport-6

#1615 Lambda execute stack trace should be not formatted with extra space
  changelogs/fragments/1615-no_formatted_with_extra_space.yml
  plugins/modules/lambda_execute.py
Labels: mergeit, backport-5, backport-6

#1614 New modules: iam_instance_profile(_info)
  changelogs/fragments/1843-iam_instance_profile.yml
  meta/runtime.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_instance_profile.py
  plugins/modules/iam_instance_profile_info.py
  tests/integration/targets/iam_instance_profile/aliases
  tests/integration/targets/iam_instance_profile/defaults/main.yml
  tests/integration/targets/iam_instance_profile/files/deny-assume.json
  tests/integration/targets/iam_instance_profile/meta/main.yml
  tests/integration/targets/iam_instance_profile/tasks/main.yml
  tests/integration/targets/iam_instance_profile/tasks/tags.yml
Labels: mergeit, backport-6

#1634 [manual backport stable-5] Lambda execute stack trace should be not formatted with extra space
  changelogs/fragments/1615-no_formatted_with_extra_space.yml
  plugins/modules/lambda_execute.py
Labels: mergeit

#1635 [manual backport stable-5] Fix typo in rds_instance docs for master_user_password (#1617)
  plugins/modules/rds_instance.py
Labels: mergeit
