Repository ansible-collections/amazon.aws, pull requests merged in 2023-12, with the labels that each got.

#1893 ec2_metadata_facts - Skip tests against 2.7 hosts when running Ansible-core >= 2.17
  tests/integration/targets/ec2_metadata_facts/templates/inventory.j2
Labels: mergeit, skip-changelog

#1892 iam_group - add support for setting the path
  changelogs/fragments/20231130-iam_group.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_group.py
  tests/integration/targets/iam_group/defaults/main.yml
  tests/integration/targets/iam_group/files/deny-all.json
  tests/integration/targets/iam_group/tasks/deletion.yml
  tests/integration/targets/iam_group/tasks/main.yml
  tests/integration/targets/iam_group/tasks/path.yml
  tests/integration/targets/iam_group/tasks/policy_update.yml
  tests/integration/targets/iam_group/tasks/users.yml
Labels: mergeit, backport-7

#1904 Prep amazon.aws 7.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1828-ec2_instance_additional_info.yml
  changelogs/fragments/1843-ec2_eip.yml
  changelogs/fragments/1843-ec2_security_group-tags.yml
  changelogs/fragments/1843-ec2_vpc_igw.yml
  changelogs/fragments/1843-ec2_vpc_route_table.yml
  changelogs/fragments/1843-ec2_vpc_subnet.yml
  changelogs/fragments/1847-s3_object-fix-false-deprecation-warning.yml
  changelogs/fragments/1848-ec2_vpc_subnet-wait-creation.yml
  changelogs/fragments/1881-allow-s3_object-to-specify-content-type-in-metadata.yml
  changelogs/fragments/20231110-sanity.yml
  changelogs/fragments/20231130-iam_group.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1909 Fix sanity workflow
  .github/workflows/sanity.yml
  .github/workflows/units.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/rds_instance_snapshot.py
  tests/unit/plugins/modules/test_ec2_ami_info.py
Labels: mergeit, skip-changelog

#1905 Prep amazon.aws 6.5.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1607-NoSuchTagSet.yml
  changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
  changelogs/fragments/1799-s3_object-bucket.yml
  changelogs/fragments/1847-s3_object-fix-false-deprecation-warning.yml
  changelogs/fragments/1848-ec2_vpc_subnet-wait-creation.yml
  changelogs/fragments/1881-allow-s3_object-to-specify-content-type-in-metadata.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1884 module_utils/elbv2 - supports update for TLS listeners
  changelogs/fragments/20231127-module_utils-elbv2-update.yaml
  plugins/module_utils/elbv2.py
  tests/unit/module_utils/test_elbv2.py
Labels: mergeit

#1912 iam_user - Add support for setting path and boundary policy
  changelogs/fragments/20231206-iam_user_path.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_user.py
  tests/integration/targets/iam_user/defaults/main.yml
  tests/integration/targets/iam_user/tasks/boundary_policy.yml
  tests/integration/targets/iam_user/tasks/deletion.yml
  tests/integration/targets/iam_user/tasks/main.yml
  tests/integration/targets/iam_user/tasks/managed_policies.yml
  tests/integration/targets/iam_user/tasks/password.yml
  tests/integration/targets/iam_user/tasks/path.yml
  tests/integration/targets/iam_user/tasks/search_group.yml
  tests/integration/targets/iam_user/tasks/tags.yml
Labels: mergeit, backport-7

#1913 Update changelog after releases 7.1.0 and 6.5.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1828-ec2_instance_additional_info.yml
  changelogs/fragments/1843-ec2_eip.yml
  changelogs/fragments/1843-ec2_security_group-tags.yml
  changelogs/fragments/1843-ec2_vpc_igw.yml
  changelogs/fragments/1843-ec2_vpc_route_table.yml
  changelogs/fragments/1843-ec2_vpc_subnet.yml
  changelogs/fragments/1847-s3_object-fix-false-deprecation-warning.yml
  changelogs/fragments/1848-ec2_vpc_subnet-wait-creation.yml
  changelogs/fragments/1881-allow-s3_object-to-specify-content-type-in-metadata.yml
  changelogs/fragments/20231110-sanity.yml
  changelogs/fragments/20231130-iam_group.yml
Labels: mergeit, skip-changelog

#1922 Remove useless tests/sanity/ignore-2.*.txt files lower than 2.14
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
Labels: mergeit, backport-7

#1921 Bump MariaDB versions for test - Amazon dropped old ones again
  tests/integration/targets/rds_instance_upgrade/defaults/main.yml
Labels: mergeit, backport-6, skip-changelog, backport-7

#1900 ansible-lint (documentation) cleanup for plugins/
  plugins/callback/aws_resource_actions.py
  plugins/inventory/aws_ec2.py
  plugins/lookup/aws_account_attribute.py
  plugins/lookup/aws_service_ip_ranges.py
  plugins/lookup/secretsmanager_secret.py
  plugins/lookup/ssm_parameter.py
  plugins/modules/autoscaling_group.py
  plugins/modules/backup_selection.py
  plugins/modules/backup_tag.py
  plugins/modules/backup_vault.py
  plugins/modules/cloudformation.py
  plugins/modules/cloudwatch_metric_alarm.py
  plugins/modules/cloudwatch_metric_alarm_info.py
  plugins/modules/cloudwatchlogs_log_group.py
  plugins/modules/cloudwatchlogs_log_group_metric_filter.py
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_eip_info.py
  plugins/modules/ec2_import_image.py
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_instance_info.py
  plugins/modules/ec2_key_info.py
  plugins/modules/ec2_security_group.py
  plugins/modules/ec2_snapshot.py
  plugins/modules/ec2_spot_instance.py
  plugins/modules/ec2_spot_instance_info.py
  plugins/modules/ec2_tag.py
  plugins/modules/ec2_vpc_dhcp_option.py
  plugins/modules/ec2_vpc_dhcp_option_info.py
  plugins/modules/ec2_vpc_igw.py
  plugins/modules/ec2_vpc_igw_info.py
  plugins/modules/ec2_vpc_nat_gateway.py
  plugins/modules/ec2_vpc_net.py
  plugins/modules/elb_classic_lb.py
  plugins/modules/iam_group.py
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_policy.py
  plugins/modules/iam_role.py
  plugins/modules/lambda.py
  plugins/modules/lambda_alias.py
  plugins/modules/lambda_event.py
  plugins/modules/rds_cluster.py
  plugins/modules/rds_global_cluster_info.py
  plugins/modules/rds_instance.py
  plugins/modules/rds_option_group.py
  plugins/modules/route53.py
  plugins/modules/route53_zone.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_object.py
  plugins/modules/sts_assume_role.py
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tox.ini
Labels: mergeit, skip-changelog, backport-7

#1927 [stable-6] changelog - fix formatting
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, skip-changelog

#1928 [stable-7] changelog - fix formatting
  changelogs/changelog.yaml
Labels: mergeit, skip-changelog

#1926 changelog - fix formatting
  changelogs/changelog.yaml
Labels: mergeit, skip-changelog

#1839 rds_cluster: add support for ServerlessV2ScalingConfiguration
  changelogs/fragments/1839-rds_cluster-add-support-for-serverless_v2_scaling_configuration.yml
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster_modify/defaults/main.yml
  tests/integration/targets/rds_cluster_modify/tasks/create_update_cluster_serverless_v2_scaling_configuration.yaml
  tests/integration/targets/rds_cluster_modify/tasks/main.yaml
Labels: mergeit

#1883 cloudwatchevent_rule: Fix json input handling for input_template
  changelogs/fragments/1883-cloudwatchevent_rule-fix-json-input-handling-for-input_template.yml
  plugins/modules/cloudwatchevent_rule.py
  tests/integration/targets/cloudwatchevent_rule/tasks/main.yml
  tests/integration/targets/cloudwatchevent_rule/tasks/test_json_input_template.yml
Labels: mergeit

#1919 s3_bucket_info - add support for bucket versioning in bucket_facts
  changelogs/fragments/20231211-s3_bucket_info-add-support-for-bucket_versioning.yml
  plugins/modules/s3_bucket_info.py
  plugins/modules/s3_object_info.py
  tests/integration/targets/s3_bucket_info/tasks/basic.yml
  tests/integration/targets/s3_bucket_info/tasks/main.yml
  tests/integration/targets/s3_object/tasks/main.yml
Labels: mergeit

#1918 ec2_instance: add support for modifying instance metadata options
  changelogs/fragments/1918-ec2_instance-add-support-to-modify-metadata-options.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_metadata_options/tasks/main.yml
Labels: mergeit

#1933 Various IAM module cleanup
  changelogs/fragments/20231219-iam-consistency.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_group.py
  plugins/modules/iam_instance_profile.py
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  plugins/modules/iam_user.py
  plugins/modules/iam_user_info.py
  tests/integration/targets/iam_instance_profile/tasks/main.yml
  tests/integration/targets/iam_role/tasks/creation_deletion.yml
  tests/integration/targets/iam_user/tasks/main.yml
  tests/unit/module_utils/iam/test_validate_iam_identifiers.py
  tests/unit/module_utils/test_get_aws_account_id.py
Labels: mergeit, backport-7
