Repository ansible-collections/amazon.aws, pull requests merged in 2023-09, with the labels that each got.

#1724 [manual backport stable-6] ec2_key - fix security vulnerability (#1704)
  changelogs/fragments/ec2_key-fix-security-vulnerability.yml
  plugins/modules/ec2_key.py
  tests/integration/targets/ec2_key/defaults/main.yml
  tests/integration/targets/ec2_key/tasks/main.yml
  tests/unit/plugins/modules/test_ec2_key.py
Labels: mergeit

#1681 cloudformation: add support for DisableRollback to upadte stack
  changelogs/fragments/1681-cloudformation-add-support-for-disable_rollback-to-update.yml
  plugins/modules/cloudformation.py
  tests/integration/targets/cloudformation/defaults/main.yml
  tests/integration/targets/cloudformation/tasks/main.yml
  tests/integration/targets/cloudformation/tasks/test_disable_rollback.yml
Labels: bug, has_issue, integration, module, tests, community_review, plugins, mergeit, backport-5, backport-6

#1725 Prep amazon.aws 6.4.0 - release_date: '2023-09-05'
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1681-cloudformation-add-support-for-disable_rollback-to-update.yml
  changelogs/fragments/1685-ssm_parameter-update-examples-to-use-fqcn.yml
  changelogs/fragments/1701-backup-selection-bugfix.yml
  changelogs/fragments/doc_update_for_keypair_nolog.yml
  changelogs/fragments/ec2_key-fix-security-vulnerability.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit

#1690 ec2_ami: Add support for OrganizationArn and OrganizationalUnitArn
  changelogs/fragments/1690-ec2_ami-add-support-org_arn-orgu_arn.yml
  plugins/modules/ec2_ami.py
  tests/integration/targets/ec2_ami/tasks/main.yml
Labels: feature, integration, module, tests, community_review, plugins, mergeit, backport-6

#1734 Changelog - 6.4.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1681-cloudformation-add-support-for-disable_rollback-to-update.yml
  changelogs/fragments/1685-ssm_parameter-update-examples-to-use-fqcn.yml
  changelogs/fragments/1701-backup-selection-bugfix.yml
  changelogs/fragments/doc_update_for_keypair_nolog.yml
  changelogs/fragments/ec2_key-fix-security-vulnerability.yml
Labels: mergeit

#1740 Add description to galaxy.yml
  README.md
  changelogs/fragments/20230906-galaxy.yml
  galaxy.yml
Labels: mergeit, backport-5, backport-6

#1742 [PR #1696/fe7057be backport][stable-5] Add a workflow (+actions) to automatically generate the GitHub Release when a valid tag is pushed
  .github/workflows/release-manual.yml
  .github/workflows/release-tag.yml
Labels: mergeit

#1745 yamllint cleanup/config
  .yamllint
  changelogs/config.yaml
  changelogs/fragments/1631-route53_health_check-added-calculcated.yml
  changelogs/fragments/1647-add-type-started-and-stopped.yml
  meta/runtime.yml
Labels: mergeit, backport-6, skip-changelog

#1741 Prep amazon.aws 5.5.4
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1685-ssm_parameter-update-examples-to-use-fqcn.yml
  changelogs/fragments/doc_update_for_keypair_nolog.yml
  galaxy.yml
Labels: mergeit

#1749 [backport][stable-6] yamllint cleanup/config (#1745)
  .yamllint
  changelogs/config.yaml
  meta/runtime.yml
Labels: mergeit, skip-changelog

#1751 Cleanup after renamed plugins
  changelogs/fragments/20230908-alias-cleanup.yml
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/main.yaml
  tests/integration/targets/setup_ec2_vpc/tasks/cleanup.yml
Labels: mergeit, backport-6

#1752 ec2_ami - fix org-owner version_added
  changelogs/fragments/20230911-ec2_ami-release.yml
  plugins/modules/ec2_ami.py
Labels: mergeit, backport-6

#1755 Promote iam_group module
  changelogs/fragments/migrate_iam_group.yml
  meta/runtime.yml
  plugins/modules/iam_group.py
  plugins/modules/iam_policy.py
  plugins/modules/iam_user.py
  tests/integration/targets/iam_group/aliases
  tests/integration/targets/iam_group/defaults/main.yml
  tests/integration/targets/iam_group/meta/main.yml
  tests/integration/targets/iam_group/tasks/main.yml
Labels: mergeit

#1764 Copy 2.16 ignore file to 2.17 (route53 'get' mode)
  tests/sanity/ignore-2.17.txt
Labels: mergeit, backport-5, backport-6

#1760 Migrate iam_role* modules and tests
  changelogs/fragments/migrate_iam_role.yml
  meta/runtime.yml
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  tests/integration/targets/iam_role/aliases
  tests/integration/targets/iam_role/defaults/main.yml
  tests/integration/targets/iam_role/files/deny-all-a.json
  tests/integration/targets/iam_role/files/deny-all-b.json
  tests/integration/targets/iam_role/files/deny-all.json
  tests/integration/targets/iam_role/files/deny-assume.json
  tests/integration/targets/iam_role/meta/main.yml
  tests/integration/targets/iam_role/tasks/boundary_policy.yml
  tests/integration/targets/iam_role/tasks/complex_role_creation.yml
  tests/integration/targets/iam_role/tasks/creation_deletion.yml
  tests/integration/targets/iam_role/tasks/description_update.yml
  tests/integration/targets/iam_role/tasks/inline_policy_update.yml
  tests/integration/targets/iam_role/tasks/main.yml
  tests/integration/targets/iam_role/tasks/max_session_update.yml
  tests/integration/targets/iam_role/tasks/parameter_checks.yml
  tests/integration/targets/iam_role/tasks/policy_update.yml
  tests/integration/targets/iam_role/tasks/role_removal.yml
  tests/integration/targets/iam_role/tasks/tags_update.yml
Labels: mergeit

#1769 Fix integration tests - rds_cluster_modify/s3_object
  tests/integration/targets/rds_cluster_modify/tasks/main.yaml
  tests/integration/targets/s3_object/tasks/copy_object_acl_disabled_bucket.yml
Labels: mergeit, backport-6

#1762 Promote iam_managed_policy module
  changelogs/fragments/migrate_iam_managed_policy.yml
  meta/runtime.yml
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_policy.py
  plugins/modules/rds_instance.py
  tests/integration/targets/iam_managed_policy/aliases
  tests/integration/targets/iam_managed_policy/defaults/main.yml
  tests/integration/targets/iam_managed_policy/meta/main.yml
  tests/integration/targets/iam_managed_policy/tasks/main.yml
Labels: mergeit

#1768 elb_application_lb_info - ensure queries for additional ALB data have retries enabled
  changelogs/fragments/1767-elb_application_lb_info-Throttling.yml
  plugins/modules/elb_application_lb_info.py
Labels: mergeit

#1763 [7.0.0] Bump minimum botocore requirements
  README.md
  changelogs/fragments/botocore.yml
  changelogs/fragments/python37.yml
  plugins/module_utils/botocore.py
  plugins/modules/backup_restore_job_info.py
  plugins/modules/ec2_ami.py
  plugins/modules/rds_cluster.py
  plugins/modules/rds_instance.py
  requirements.txt
  tests/config.yml
  tests/integration/constraints.txt
  tests/integration/targets/aws_az_info/tasks/main.yml
  tests/integration/targets/ec2_ami/meta/main.yml
  tests/integration/targets/ec2_ami/tasks/main.yml
  tests/integration/targets/ec2_ami_tpm/meta/main.yml
  tests/integration/targets/ec2_ami_tpm/tasks/main.yml
  tests/integration/targets/rds_cluster_multi_az/meta/main.yml
  tests/integration/targets/rds_cluster_multi_az/tasks/main.yml
  tests/unit/constraints.txt
  tests/unit/module_utils/modules/ansible_aws_module/test_minimal_versions.py
  tests/unit/plugins/modules/test_ec2_ami.py
Labels: mergeit, do_not_backport

#1705 rds_cluster: add support for removing cluster from global db
  changelogs/fragments/1705-rds_cluster-add-support-remove-cluster-from-global-db.yml
  plugins/module_utils/rds.py
  plugins/module_utils/waiters.py
  plugins/modules/rds_cluster.py
  tests/integration/requirements.yml
  tests/integration/targets/rds_cluster_modify/defaults/main.yml
  tests/integration/targets/rds_cluster_modify/tasks/main.yaml
  tests/integration/targets/rds_cluster_modify/tasks/remove_from_global_db.yaml
Labels: feature, integration, module, tests, community_review, plugins, mergeit

#1778 elb_application_lb_info - Add parameters to skip fetching some data
  changelogs/fragments/1778-elb_application_lb_info-fetch-subsets.yml
  plugins/modules/elb_application_lb_info.py
  tests/integration/targets/elb_application_lb/tasks/main.yml
Labels: mergeit
