Repository ansible-collections/amazon.aws, pull requests merged in 2023-05, with the labels that each got.

#1498 Add stable-* branch to GitHub Workflow
  .github/workflows/tests.yml
Labels: mergeit

#1501 Use engine: aurora-mysql rather than aurora
  changelogs/fragments/20230502-rds_cluster-engine_version.yml
  tests/integration/targets/rds_cluster_restore/defaults/main.yml
Labels: mergeit, backport-5

#1505 Ensure ec2_instance tests filter correctly
  changelogs/fragments/1505-ec2_instance_test_fixes.yml
  tests/integration/targets/ec2_instance_instance_multiple/tasks/main.yml
Labels: mergeit, backport-5

#1495 [manual backport stable-5] new modules: lambda_layer and lambda_layer_info (#1095)
  meta/runtime.yml
  plugins/modules/lambda_layer.py
  plugins/modules/lambda_layer_info.py
  tests/integration/targets/lambda_layer/aliases
  tests/integration/targets/lambda_layer/defaults/main.yml
  tests/integration/targets/lambda_layer/tasks/main.yml
  tests/unit/plugins/modules/test_lambda_layer.py
  tests/unit/plugins/modules/test_lambda_layer_info.py
Labels: mergeit

#1504 Use engine: aurora-mysql rather than aurora
  changelogs/fragments/20230502-rds_cluster-engine.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/defaults/main.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_modify.yml
Labels: mergeit

#1492 [manual backport stable-5] lambda - add support for layers when creating or updating lambda functions (#1118)
  changelogs/fragments/lambda-add-support-for-layers.yml
  plugins/modules/lambda.py
  tests/integration/targets/lambda/defaults/main.yml
  tests/integration/targets/lambda/meta/main.yml
  tests/integration/targets/lambda/tasks/main.yml
Labels: mergeit

#1508 Use engine: 'aurora-mysql' rather than engine: 'aurora' in rds_cluster_snapshot integration tests
  changelogs/fragments/20230503-rds_cluster-engine-rds_cluster_snapshot.yml
  tests/integration/targets/rds_cluster_snapshot/defaults/main.yml
Labels: mergeit

#1488 [manual backport stable-5] ec2_metadata_facts: Add support to query instance tags in metadata (#1186)
  changelogs/fragments/1186-ec2_metadata_facts-query-instance-metadata-tags.yml
  plugins/modules/ec2_metadata_facts.py
  tests/integration/targets/ec2_metadata_facts/meta/main.yml
  tests/integration/targets/ec2_metadata_facts/playbooks/setup.yml
  tests/integration/targets/ec2_metadata_facts/playbooks/test_metadata.yml
Labels: mergeit

#1482 [manual backport stable-5] Pick up app_callback -> set_password rather than app_callback -> set_passwd
  changelogs/fragments/1258-ec2_instance.yml
  changelogs/fragments/20230424-ec2_instance-app_callback.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_block_devices/defaults/main.yml
  tests/integration/targets/ec2_instance_checkmode_tests/defaults/main.yml
  tests/integration/targets/ec2_instance_cpu_options/defaults/main.yml
  tests/integration/targets/ec2_instance_default_vpc_tests/defaults/main.yml
  tests/integration/targets/ec2_instance_ebs_optimized/defaults/main.yml
  tests/integration/targets/ec2_instance_external_resource_attach/defaults/main.yml
  tests/integration/targets/ec2_instance_hibernation_options/defaults/main.yml
  tests/integration/targets/ec2_instance_iam_instance_role/defaults/main.yml
  tests/integration/targets/ec2_instance_instance_minimal/defaults/main.yml
  tests/integration/targets/ec2_instance_instance_multiple/defaults/main.yml
  tests/integration/targets/ec2_instance_instance_no_wait/defaults/main.yml
  tests/integration/targets/ec2_instance_metadata_options/defaults/main.yml
  tests/integration/targets/ec2_instance_security_group/defaults/main.yml
  tests/integration/targets/ec2_instance_state_config_updates/defaults/main.yml
  tests/integration/targets/ec2_instance_tags_and_vpc_settings/defaults/main.yml
  tests/integration/targets/ec2_instance_termination_protection/defaults/main.yml
  tests/integration/targets/ec2_instance_uptime/defaults/main.yml
  tests/integration/targets/ec2_snapshot/tasks/main.yml
  tests/integration/targets/setup_ec2_instance_env/defaults/main.yml
  tests/integration/targets/setup_ec2_instance_env/tasks/main.yml
Labels: mergeit

#1491 [manual backport stable-5] rds_cluster - update list of supported engines (#1191)
  changelogs/fragments/1191-rds_cluster-new_options.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster_multi_az/aliases
  tests/integration/targets/rds_cluster_multi_az/defaults/main.yml
  tests/integration/targets/rds_cluster_multi_az/meta/main.yml
  tests/integration/targets/rds_cluster_multi_az/tasks/main.yml
Labels: mergeit

#1493 [manual backport stable-5] rds - add the engine_mode parameter (#941)
  changelogs/fragments/rds_cluster_engine_mode.yaml
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster/roles/rds_cluster/defaults/main.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_create.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_create_sgs.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_modify.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_promote.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_restore.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_tag.yml
  tests/integration/targets/rds_cluster_snapshot/defaults/main.yml
  tests/integration/targets/rds_cluster_snapshot/tasks/main.yml
  tests/integration/targets/rds_instance_aurora/aliases
  tests/integration/targets/rds_instance_aurora/tasks/main.yml
Labels: mergeit

#1475 rds_instance: fix promotion_tier type
  changelogs/fragments/1475-rds_instance-promotion-tier.yml
  plugins/modules/rds_instance.py
Labels: mergeit, backport-5

#1511 s3_bucket - Ensure public_access settings are configured before policies
  changelogs/fragments/1511-s3_bucket-public_access.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/acl.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/complex.yml
Labels: mergeit

#1512 [stable-5] [backport/1511] s3_bucket - Ensure public_access settings are configured before policies
  changelogs/fragments/1511-s3_bucket-public_access.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/acl.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/complex.yml
Labels: mergeit

#1514 [manual backport stable-5] rds_instance: fix promotion_tier type (#1475)
  changelogs/fragments/1475-rds_instance-promotion-tier.yml
  plugins/modules/rds_instance.py
Labels: mergeit

#1513 Bulk migration to Python 3.6 f-strings (2)
  changelogs/fragments/fstring-2.yml
  plugins/inventory/aws_rds.py
  plugins/module_utils/rds.py
  plugins/modules/rds_cluster.py
  plugins/modules/rds_cluster_snapshot.py
  plugins/modules/rds_instance.py
  plugins/modules/rds_instance_info.py
  plugins/modules/rds_instance_snapshot.py
  plugins/modules/rds_param_group.py
  plugins/modules/rds_snapshot_info.py
Labels: mergeit

#1484 Fix version_added
  changelogs/fragments/fix_version_added.yml
  changelogs/fragments/lambda-add-support-for-layers.yml
  changelogs/fragments/lambda_layer_info-add-parameter-layer_version.yml
  changelogs/fragments/rds_cluster_engine_mode.yaml
  plugins/modules/cloudwatch_metric_alarm.py
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_metadata_facts.py
  plugins/modules/ec2_vpc_nat_gateway.py
  plugins/modules/kms_key.py
  plugins/modules/lambda.py
  plugins/modules/lambda_event.py
  plugins/modules/lambda_layer.py
  plugins/modules/lambda_layer_info.py
  plugins/modules/rds_cluster.py
Labels: mergeit, backport-5

#1517 [stable-5] Fix version_added (#1484)
  changelogs/fragments/fix_version_added.yml
  changelogs/fragments/lambda-add-support-for-layers.yml
  changelogs/fragments/rds_cluster_engine_mode.yaml
  plugins/modules/cloudwatch_metric_alarm.py
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_metadata_facts.py
  plugins/modules/ec2_vpc_nat_gateway.py
  plugins/modules/kms_key.py
  plugins/modules/lambda.py
  plugins/modules/lambda_event.py
  plugins/modules/lambda_layer.py
  plugins/modules/lambda_layer_info.py
  plugins/modules/rds_cluster.py
Labels: mergeit

#1518 Flag RSA example in unit test to be ignored by GitLeaks
  tests/unit/plugins/modules/test_ec2_key.py
Labels: mergeit

#1520 Prepare release 5.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1037-ec2_ami-add-support-for-boot_mode-tpm_support-uefi_data.yml
  changelogs/fragments/1133-add_metrics_cloudwatch.yml
  changelogs/fragments/1186-ec2_metadata_facts-query-instance-metadata-tags.yml
  changelogs/fragments/1191-rds_cluster-new_options.yml
  changelogs/fragments/1209-lambda_event-add-support-for-function_response_types.yml
  changelogs/fragments/1258-ec2_instance.yml
  changelogs/fragments/1267-ec2_vpc_nat_gateway_connectivitytype.yml
  changelogs/fragments/1290-create_multi_region_key.yml
  changelogs/fragments/1440-cloudwatch_metric_alarm-fix-change-detection.yml
  changelogs/fragments/1457-lambda_info-fix-env-var-in-output.yml
  changelogs/fragments/1474-ec2_vol.yml
  changelogs/fragments/1475-rds_instance-promotion-tier.yml
  changelogs/fragments/1477-elbv2-botocore.yml
  changelogs/fragments/1505-ec2_instance_test_fixes.yml
  changelogs/fragments/1511-s3_bucket-public_access.yml
  changelogs/fragments/20230424-ec2_instance-app_callback.yml
  changelogs/fragments/20230502-rds_cluster-engine.yml
  changelogs/fragments/20230503-rds_cluster-engine-rds_cluster_snapshot.yml
  changelogs/fragments/fix_version_added.yml
  changelogs/fragments/lambda-add-support-for-layers.yml
  changelogs/fragments/rds_cluster_engine_mode.yaml
  galaxy.yml
Labels: mergeit

#1522 Prepare 4.5.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1071-ec2_vol_tags_idempotent.yaml
  changelogs/fragments/1357-subnet-example.yml
  changelogs/fragments/1395-s3-encryption.yml
  changelogs/fragments/unit-tests_test_ec2_key_only.yaml
  galaxy.yml
  tests/unit/plugins/modules/test_ec2_key.py
Labels: mergeit

#1525 Update changelog with the amazon.aws 5.5.0 and 4.5.0 info
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1037-ec2_ami-add-support-for-boot_mode-tpm_support-uefi_data.yml
  changelogs/fragments/1133-add_metrics_cloudwatch.yml
  changelogs/fragments/1186-ec2_metadata_facts-query-instance-metadata-tags.yml
  changelogs/fragments/1191-rds_cluster-new_options.yml
  changelogs/fragments/1209-lambda_event-add-support-for-function_response_types.yml
  changelogs/fragments/1258-ec2_instance.yml
  changelogs/fragments/1267-ec2_vpc_nat_gateway_connectivitytype.yml
  changelogs/fragments/1290-create_multi_region_key.yml
  changelogs/fragments/1440-cloudwatch_metric_alarm-fix-change-detection.yml
  changelogs/fragments/1457-lambda_info-fix-env-var-in-output.yml
  changelogs/fragments/1474-ec2_vol.yml
  changelogs/fragments/1475-rds_instance-promotion-tier.yml
  changelogs/fragments/1477-elbv2-botocore.yml
  changelogs/fragments/1505-ec2_instance_test_fixes.yml
  changelogs/fragments/1511-s3_bucket-public_access.yml
  changelogs/fragments/20230424-ec2_instance-app_callback.yml
  changelogs/fragments/fix_version_added.yml
  changelogs/fragments/lambda-add-support-for-layers.yml
  changelogs/fragments/rds_cluster_engine_mode.yaml
Labels: mergeit

#1526 aws_ec2 inventory - migration to Python 3.6 f-strings
  changelogs/fragments/fstring-ec2_inv.yml
  plugins/inventory/aws_ec2.py
  plugins/modules/ec2_vpc_subnet.py
  tests/integration/targets/inventory_aws_ec2/tasks/setup.yml
Labels: mergeit

#1531 ec2_vpc_endpoint - test flake
  changelogs/fragments/endpoint.yml
  tests/integration/targets/ec2_vpc_endpoint/tasks/main.yml
Labels: mergeit, backport-5

#1524 Add flake8 and black to tox.ini
  changelogs/fragments/add_linters_to_tox.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/ec2_eip.py
  plugins/modules/rds_instance.py
  tox.ini
Labels: mergeit

#1527 Bulk migration to Python 3.6 f-strings (3)
  changelogs/fragments/fstring-3.yml
  plugins/module_utils/acm.py
  plugins/module_utils/backup.py
  plugins/module_utils/cloudfront_facts.py
  plugins/module_utils/direct_connect.py
  plugins/module_utils/elbv2.py
  plugins/module_utils/iam.py
  plugins/module_utils/policy.py
  plugins/module_utils/route53.py
  plugins/module_utils/s3.py
  plugins/module_utils/urls.py
Labels: mergeit

#1529 Bulk migration to Python 3.6 f-strings (4)
  changelogs/fragments/fstring-4.yml
  plugins/module_utils/ec2.py
  plugins/module_utils/modules.py
  plugins/module_utils/tagging.py
  plugins/module_utils/waiters.py
Labels: mergeit

#1530 backup_selection* new modules
  changelogs/fragments/backup_add_backup_selections_logic.yml
  meta/runtime.yml
  plugins/module_utils/backup.py
  plugins/modules/backup_selection.py
  plugins/modules/backup_selection_info.py
  tests/integration/targets/backup_selection/aliases
  tests/integration/targets/backup_selection/defaults/main.yml
  tests/integration/targets/backup_selection/files/backup-policy.json
  tests/integration/targets/backup_selection/tasks/main.yml
Labels: mergeit

#1535 module_utils/backup - explicitly pass resource to get_backup_tags
  changelogs/fragments/backup_resource.yml
  plugins/module_utils/backup.py
  plugins/modules/backup_tag.py
  plugins/modules/backup_tag_info.py
  plugins/modules/backup_vault.py
  plugins/modules/backup_vault_info.py
Labels: mergeit

#1536 backup_selection_info - ensure result is returned as snake_case rather than CamelCase
  changelogs/fragments/backup_selection-return_snake_case.yml
  plugins/modules/backup_selection_info.py
  tests/integration/targets/backup_selection/tasks/main.yml
Labels: mergeit

#1446 Add backup_plan and backup_plan_info modules
  changelogs/fragments/1446-backup_plan-add-new-module.yml
  meta/runtime.yml
  plugins/module_utils/backup.py
  plugins/modules/backup_plan.py
  plugins/modules/backup_plan_info.py
  tests/integration/targets/backup_plan/aliases
  tests/integration/targets/backup_plan/defaults/main.yml
  tests/integration/targets/backup_plan/tasks/main.yml
Labels: new_plugin, new_module, new_contributor, module, plugins, mergeit

#1519 Add Github Action details to CI.md
  CI.md
  CONTRIBUTING.md
  README.md
Labels: mergeit

#1542 Fix 6.0.0 changelog formatting
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, backport-6

#1541 Update stable-6 docs links from main to stable-6
  README.md
  galaxy.yml
Labels: mergeit

#1540 Bump main to 7.0.0-dev0
  changelogs/fragments/7.0.0-urls.yml
  galaxy.yml
  plugins/module_utils/common.py
  plugins/module_utils/urls.py
Labels: mergeit

#1538 s3_bucket: fix VersionId==null when s3 object not versioned
  changelogs/fragments/1538-s3-null.yml
  plugins/modules/s3_bucket.py
Labels: mergeit, backport-6

#1464 ec2_snapshot, ec2_snapshot_info: Add support to modify snapshot share permissions
  changelogs/fragments/1464-ec2_snapshot-ec2_snapshot_info-support-modifying-create-volume-permissions.yml
  plugins/modules/ec2_snapshot.py
  plugins/modules/ec2_snapshot_info.py
  tests/integration/targets/ec2_snapshot/tasks/main.yml
  tests/integration/targets/ec2_snapshot/tasks/test_modify_create_volume_permissions.yml
Labels: mergeit, backport-6

#1549 s3_object - fix regression related to leading / in object key names
  changelogs/fragments/1548-s3_object-leading-slash.yml
  plugins/modules/s3_object.py
  tests/integration/targets/s3_object/tasks/copy_object_acl_disabled_bucket.yml
  tests/integration/targets/s3_object/tasks/delete_bucket.yml
  tests/integration/targets/s3_object/tasks/main.yml
  tests/unit/plugins/modules/test_s3_object.py
Labels: mergeit, backport-6

#1555 s3_object - deprecate leading slash in object keys
  changelogs/fragments/1548-s3_object-leading-slash-deprecate.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-6

#1553 Use pytest-ansible instead of pytest-ansible-units
  changelogs/fragments/add-pytest-ansible.yml
  test-requirements.txt
  tests/unit/plugins/modules/test_lambda_layer.py
  tox.ini
Labels: mergeit

#1560 Temporarily Revert "ec2_snapshot, ec2_snapshot_info: Add support to modify snapshotot share permissions (#1464) (#1546)"
  changelogs/fragments/1464-ec2_snapshot-ec2_snapshot_info-support-modifying-create-volume-permissions.yml
  changelogs/fragments/1560-revert_1546.yml
  plugins/modules/ec2_snapshot.py
  plugins/modules/ec2_snapshot_info.py
  tests/integration/targets/ec2_snapshot/tasks/main.yml
  tests/integration/targets/ec2_snapshot/tasks/test_modify_create_volume_permissions.yml
Labels: mergeit

#1564 Switch to Ansible Galaxy compatible requirements files for tests
  changelogs/fragments/test-reqs.yml
  tests/integration/requirements.yml
  tests/requirements.yml
Labels: mergeit, backport-5, backport-6

#1562 [Manual backport to stable-6] ec2_snapshot, ec2_snapshot_info: Add support to modify snapshot share permissions (#1464)
  changelogs/fragments/1464-ec2_snapshot-ec2_snapshot_info-support-modifying-create-volume-permissions.yml
  plugins/modules/ec2_snapshot.py
  plugins/modules/ec2_snapshot_info.py
  tests/integration/targets/ec2_snapshot/tasks/main.yml
  tests/integration/targets/ec2_snapshot/tasks/test_modify_create_volume_permissions.yml
Labels: mergeit

#1563 elb_application_lb - fix missing attributes on create
  changelogs/fragments/1510-elb_application_lb-fix-alb-specific-attributes-not-added-on-create.yml
  plugins/modules/elb_application_lb.py
  tests/integration/targets/elb_application_lb/defaults/main.yml
  tests/integration/targets/elb_application_lb/tasks/main.yml
  tests/integration/targets/elb_application_lb/templates/policy.json
Labels: mergeit, backport-5, backport-6

#1499 Add black and github workflow rework
  .github/workflows/all_green_check.yml
  .github/workflows/ansible-bot.yml
  .github/workflows/changelog_and_linters.yml
  .github/workflows/darker-pr.yml
  .github/workflows/sanity.yml
  .github/workflows/tests.yml
  .github/workflows/units.yml
  .github/workflows/update-variables.yml
  tox.ini
Labels: mergeit

#1576 ec2_instance - fix idempotency issue when attaching ENI to isntance
  changelogs/fragments/ec2_instance-eni-attach-idempotency.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_external_resource_attach/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1575 ec2_metadata_facts - Handle decompression when EC2 instance user-data is compressed
  changelogs/fragments/20230526-ec2_mertadata_facts-handle_compressed_user_data.yml
  plugins/modules/ec2_metadata_facts.py
  tests/unit/plugins/modules/test_ec2_metadata_facts.py
Labels: mergeit, backport-5, backport-6

#1578 Remove unrelated snapshot comment from rds_instance state docs
  changelogs/fragments/1578-rds-instance-docs.yml
  plugins/modules/rds_instance.py
Labels: mergeit, backport-5, backport-6
