Repository ansible-collections/amazon.aws, pull requests merged in 2023-07, with the labels that each got.

#1608 s3_object - allow recursive copy of all objects in S3 bucket
  changelogs/fragments/20230612-s3_object-support-copy-objects-recursively.yml
  plugins/modules/s3_object.py
  tests/integration/targets/s3_object/tasks/copy_recursively.yml
  tests/integration/targets/s3_object/tasks/main.yml
  tests/unit/plugins/modules/test_s3_object.py
Labels: mergeit

#1637 Add suggestion for isort config
  changelogs/fragments/20230702-isort.yml
  pyproject.toml
Labels: mergeit

#1633 Document and validate backup_selection conditions suboptions
  changelogs/fragments/1633-backup-selection-conditions.yml
  plugins/module_utils/backup.py
  plugins/modules/backup_selection.py
  tests/integration/targets/backup_selection/tasks/main.yml
Labels: mergeit, backport-6

#1589 cloudwatchevent_rule should return false when there is no change done to the rule
  changelogs/fragments/1589-return_false_when_no_change..yml
  plugins/modules/cloudwatchevent_rule.py
  tests/integration/targets/cloudwatchevent_rule/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1632 ec2_vpc_nat_gateway - changes to no allocate eip address when connectivity_type=private
  changelogs/fragments/1632-changes-to-no-allocate-eip-when-connectivity_type=private.yml
  plugins/modules/ec2_vpc_nat_gateway.py
  tests/integration/targets/ec2_vpc_nat_gateway/tasks/main.yml
Labels: mergeit, backport-5, backport-6

#1604 ec2_vpc_nat_gateway show fails if EIP doesn't exist
  changelogs/fragments/1604-c2_vpc_nat_gateway-fails-silently.yml
  plugins/modules/ec2_vpc_nat_gateway.py
  tests/integration/targets/ec2_vpc_nat_gateway/tasks/main.yml
Labels: mergeit, backport-6

#1643 Prep amazon.aws 6.2.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1589-return_false_when_no_change..yml
  changelogs/fragments/1604-c2_vpc_nat_gateway-fails-silently.yml
  changelogs/fragments/1615-no_formatted_with_extra_space.yml
  changelogs/fragments/1632-changes-to-no-allocate-eip-when-connectivity_type=private.yml
  changelogs/fragments/1633-backup-selection-conditions.yml
  changelogs/fragments/1843-iam_instance_profile.yml
  changelogs/fragments/1846-arn-validation.yml
  changelogs/fragments/20230506-autoscaling_group-fix_sanity.yml
  changelogs/fragments/202306012-backup_plan-remove-none-from-nested-params.yml
  changelogs/fragments/20230612-backup_vault-fix-tag-update.yml
  changelogs/fragments/20230627-ci-fixup.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit

#1658 fix sanity - add devel and python3.9 from matrix exclude
  .github/workflows/sanity.yml
  .github/workflows/units.yml
Labels: bug, python3, community_review, needs_triage, small_patch, mergeit

#1649 backup_selection - Documentation fix
  changelogs/fragments/20230707-backup_selection-doc-fix.yml
  plugins/modules/backup_selection.py
Labels: merge_commit, needs_rebase, owner_pr, module, docs, plugins, mergeit, backport-6

#1648 Update changelog to reflect the 6.2.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1589-return_false_when_no_change..yml
  changelogs/fragments/1604-c2_vpc_nat_gateway-fails-silently.yml
  changelogs/fragments/1615-no_formatted_with_extra_space.yml
  changelogs/fragments/1632-changes-to-no-allocate-eip-when-connectivity_type=private.yml
  changelogs/fragments/1633-backup-selection-conditions.yml
  changelogs/fragments/1843-iam_instance_profile.yml
  changelogs/fragments/1846-arn-validation.yml
  changelogs/fragments/20230506-autoscaling_group-fix_sanity.yml
  changelogs/fragments/202306012-backup_plan-remove-none-from-nested-params.yml
  changelogs/fragments/20230612-backup_vault-fix-tag-update.yml
  changelogs/fragments/20230627-ci-fixup.yml
Labels: community_review, needs_triage, docs, mergeit

#1587 Drop vendored copy of LooseVersion
  PSF-license.txt
  changelogs/fragments/1587-LooseVersion.yml
  plugins/module_utils/_version.py
  plugins/module_utils/botocore.py
  plugins/module_utils/version.py
Labels: feature, module_utils, python3, community_review, needs_triage, plugins, mergeit

#1663 Allow user to associate rds cluster with a global rds cluster
  changelogs/fragments/20230725-rds_cluster-fix.yml
  plugins/modules/rds_cluster.py
Labels: bug, merge_commit, needs_rebase, owner_pr, module, plugins, mergeit, backport-5, backport-6

#1671 Fix rds_cluster tests on stable-5 branch
  tests/integration/targets/rds_cluster/roles/rds_cluster/defaults/main.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/main.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_create.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_create_sgs.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_promote.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_restore.yml
  tests/integration/targets/rds_cluster/roles/rds_cluster/tasks/test_tag.yml
Labels: bug, integration, tests, community_review, plugins, mergeit, skip-changelog

#1657 rds_cluster - enable creation or modification of AllocatedStorage, DBClusterInstanceClass, StorageType, Iops, and EngineMode
  changelogs/fragments/20230713-rds_cluster-fix_params_passage.yml
  plugins/modules/rds_cluster.py
Labels: bug, owner_pr, module, community_review, plugins, mergeit, backport-5, backport-6

#1673 [stable-5] Delete ansible-bot workflow
  .github/workflows/ansible-bot.yml
Labels: bug, community_review, needs_triage, mergeit, skip-changelog
