Repository ansible-collections/amazon.aws, pull requests merged in 2023-03, with the labels that each got.

#1394 Cleanup and move tasks (vs playbooks) in inventory tests
  changelogs/fragments/1394-lint.yml
  plugins/modules/ec2_vpc_net.py
  tests/integration/targets/inventory_aws_ec2/playbooks/manage_ec2_instances.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/populate_cache.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/tasks
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_concatenation.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_constructed.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostnames_using_tags.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostnames_using_tags_classic.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_include_or_exclude_filters.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_literal_string.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_use_contrib_script_keys.yml
  tests/integration/targets/inventory_aws_ec2/tasks/setup.yml
  tests/integration/targets/inventory_aws_ec2/tasks/tear_down.yml
  tests/integration/targets/inventory_aws_ec2/tasks/test_refresh_inventory.yml
  tests/integration/targets/inventory_aws_rds/playbooks/test_refresh_inventory.yml
Labels: mergeit

#1395 Disable S3 tests related to removing bucket encryption
  changelogs/fragments/1395-s3-encryption.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_bucket_key.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_kms.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_sse.yml
Labels: mergeit, backport-4, backport-5

#1300 Support multiple VPCs for a route53_zone
  changelogs/fragments/1299-route53_zone-multi-vpc.yml
  plugins/modules/route53_zone.py
  tests/integration/targets/route53_zone/tasks/main.yml
Labels: new_contributor, feature, integration, module, tests, community_review, plugins, mergeit, backport-5

#1400 Fix 'compatibility' typo
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1400-typo.yml
  changelogs/fragments/release-6-botocore.yml
  plugins/doc_fragments/aws_credentials.py
  plugins/doc_fragments/common.py
  tests/integration/targets/cloudwatchlogs/tasks/create-delete-tags.yml
  tests/unit/module_utils/test_iam.py
Labels: mergeit, backport-4, backport-5

#1405 [stable-5] Fix 'compatibility' typo
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1400-typo.yml
  tests/integration/targets/cloudwatchlogs/tasks/create-delete-tags.yml
  tests/sanity/ignore-2.9.txt
  tests/unit/module_utils/test_iam.py
Labels: mergeit

#1372 s3_bucket: object lock enabled
  changelogs/fragments/1347-s3-object-lock-enabled.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/object_lock.yml
Labels: mergeit

#1409 Prep amazon.aws 5.3.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1226-defaults.yml
  changelogs/fragments/1270-elbv2-fixes.yml
  changelogs/fragments/1299-route53_zone-multi-vpc.yml
  changelogs/fragments/1347-s3-object-lock-enabled.yml
  changelogs/fragments/1353-revert-env-fallback.yml
  changelogs/fragments/1357-subnet-example.yml
  changelogs/fragments/1368-empty_bucket_policy.yml
  changelogs/fragments/1383-ec2_key-fix-idempotency-issue-when-creating-existing-key-with-same-key-material.yaml
  changelogs/fragments/1384-cloudtrail-disable_encryption.yml
  changelogs/fragments/1395-s3-encryption.yml
  changelogs/fragments/1400-typo.yml
  changelogs/fragments/20230204-sanity.yml
  changelogs/fragments/20230220-inventory_docs_ec2_aws.yml
  changelogs/fragments/389-ssm_parameter-versioned_test.yml
  changelogs/fragments/964-ec2_instance-return-instances.yml
  changelogs/fragments/unit-tests_test_ec2_key_only.yaml
  galaxy.yml
Labels: mergeit

#1410 5.3.0 Release documentation
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1174-module_params.yml
  changelogs/fragments/1226-defaults.yml
  changelogs/fragments/1266-rds_instance_gp3_support.yaml
  changelogs/fragments/1270-elbv2-fixes.yml
  changelogs/fragments/1277-lambda-int-test-other-lambdas.yml
  changelogs/fragments/1283-aws_ec2_inventory_compose_doc_examples.yml
  changelogs/fragments/1299-route53_zone-multi-vpc.yml
  changelogs/fragments/1347-s3-object-lock-enabled.yml
  changelogs/fragments/1357-subnet-example.yml
  changelogs/fragments/1368-empty_bucket_policy.yml
  changelogs/fragments/1383-ec2_key-fix-idempotency-issue-when-creating-existing-key-with-same-key-material.yaml
  changelogs/fragments/1384-cloudtrail-disable_encryption.yml
  changelogs/fragments/1395-s3-encryption.yml
  changelogs/fragments/1400-typo.yml
  changelogs/fragments/20230204-sanity.yml
  changelogs/fragments/20230220-inventory_docs_ec2_aws.yml
  changelogs/fragments/389-ssm_parameter-versioned_test.yml
  changelogs/fragments/964-ec2_instance-return-instances.yml
  changelogs/fragments/integration_tests_max_duration_increase.yaml
  changelogs/fragments/rds_instance_split_the_integration_test-suite.yaml
  changelogs/fragments/rds_mariadb_version-10.6.10.yml
  changelogs/fragments/unit-tests_test_ec2_key_only.yaml
Labels: mergeit

#1406 s3_bucket - be more forgiving when missing 'get' permissions for a parameter we're not trying to set
  changelogs/fragments/1352-s3-limited-permissions.yml
  plugins/modules/s3_bucket.py
Labels: mergeit

#1413 release documentation - add antsibull-changelog command and fix fragment location
  docs/docsite/rst/collection_release.rst
Labels: mergeit

#1369 inventory aws_ec2 - add ssm_inventory inventory into hostvars
  changelogs/fragments/1369-inventory_aws_ec2-add-support-for-ssm-inventory.yml
  docs/docsite/rst/aws_ec2_guide.rst
  plugins/inventory/aws_ec2.py
  tests/integration/targets/inventory_aws_ec2/playbooks/files/ec2-trust-policy.json
  tests/integration/targets/inventory_aws_ec2/playbooks/library/test_get_ssm_inventory.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_inventory_ssm.yml
  tests/integration/targets/inventory_aws_ec2/runme.sh
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_ssm.yml.j2
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit, backport-5

#1414 fix link README
  README.md
Labels: mergeit

#1402 ec2_spot_instance: add parameter to enable terminating spot instances when cancelling request
  changelogs/fragments/1402-ec2_spot_instance-ability-to-terminate-instances.yml
  plugins/modules/ec2_spot_instance.py
  tests/integration/targets/ec2_spot_instance/tasks/main.yaml
  tests/integration/targets/ec2_spot_instance/tasks/terminate_associated_instances.yml
Labels: mergeit, backport-5

#1425 Automate update of collection variable using gha
  .github/workflows/update-variables.yml
Labels: mergeit

#1428 fix github action
  .github/workflows/update-variables.yml
Labels: mergeit

#1416 inventory_aws_ec2 - integration tests update
  changelogs/fragments/inventory_aws_ec2_update.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/library/test_get_ssm_inventory.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_inventory_ssm.yml
Labels: mergeit

#1419 route53_info: fix "key error" for health_check operations
  changelogs/fragments/1419-route53_info-fix-keyerror-for-healthcheck-operations.yml
  plugins/modules/route53_info.py
  tests/integration/targets/route53_health_check/tasks/main.yml
Labels: mergeit, backport-5

#1433 route53_health_check - Bump version-added on measure_latency
  changelogs/fragments/5.4.0-route53_health_check.yml
  plugins/modules/route53_health_check.py
Labels: mergeit

#1191 rds_cluster - update list of supported engines
  changelogs/fragments/1191-rds_cluster-new_options.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster_multi_az/aliases
  tests/integration/targets/rds_cluster_multi_az/defaults/main.yml
  tests/integration/targets/rds_cluster_multi_az/meta/main.yml
  tests/integration/targets/rds_cluster_multi_az/tasks/main.yml
Labels: bug, needs_rebase, integration, module, module_utils, tests, plugins, mergeit, backport-5

#1420 [PR #1359/31570048 backport] [stable-5] ec2_metadata_facts - fix AttributeError when running on older managed hosts
  changelogs/fragments/1358-ec2_metadata_facts.yml
  plugins/modules/ec2_metadata_facts.py
  tests/integration/targets/ec2_metadata_facts/playbooks/setup.yml
  tests/integration/targets/ec2_metadata_facts/playbooks/teardown.yml
  tests/integration/targets/ec2_metadata_facts/templates/inventory.j2
Labels: mergeit

#1427 new modules: backup_tag and backup_tag_info
  changelogs/fragments/1427-backup_tag-and_backup_tag_info-add-new-module.yml
  meta/runtime.yml
  plugins/module_utils/backup.py
  plugins/modules/backup_tag.py
  plugins/modules/backup_tag_info.py
  tests/integration/targets/backup_tag/aliases
  tests/integration/targets/backup_tag/defaults/main.yml
  tests/integration/targets/backup_tag/meta/main.yml
  tests/integration/targets/backup_tag/tasks/main.yml
  tests/integration/targets/backup_tag/vars/main.yml
Labels: mergeit

#1441 Prepare release 5.4.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1071-ec2_vol_tags_idempotent.yaml
  changelogs/fragments/1201-route53_health_check-add-support-for-latency-graphs.yml
  changelogs/fragments/1358-ec2_metadata_facts.yml
  changelogs/fragments/1402-ec2_spot_instance-ability-to-terminate-instances.yml
  changelogs/fragments/1419-route53_info-fix-keyerror-for-healthcheck-operations.yml
  changelogs/fragments/1437-rds_instance-gp3-tagging-bugfix.yml
  changelogs/fragments/5.4.0-route53_health_check.yml
  galaxy.yml
Labels: mergeit

#1440 Don't consider prop 'StateTransitionedTimestamp' in change detection
  changelogs/fragments/1440-cloudwatch_metric_alarm-fix-change-detection.yml
  plugins/modules/cloudwatch_metric_alarm.py
Labels: mergeit

#1448 Replace pycrypto test dependency
  changelogs/fragments/1448-replace-pycrypto.yml
  test-requirements.txt
  tests/integration/requirements.txt
Labels: mergeit

#1435 new_module: backup_restore_job_info
  changelogs/fragments/1435-backup_restore_job_info-add-new-module.yml
  plugins/modules/backup_restore_job_info.py
  tests/unit/plugins/modules/test_backup_restore_job_info.py
Labels: new_plugin, new_module, module, tests, community_review, needs_triage, plugins, mergeit
