Repository ansible-collections/amazon.aws, pull requests merged in 2023-10, with the labels that each got.

#1782 Prepare release 6.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1690-ec2_ami-add-support-org_arn-orgu_arn.yml
  changelogs/fragments/1714-parameters.yml
  changelogs/fragments/1767-elb_application_lb_info-Throttling.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/20230911-ec2_ami-release.yml
  changelogs/fragments/ec2_region.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: skip-changelog

#1795 aws_az_info - add example of filtering by state
  plugins/modules/aws_az_info.py
Labels: mergeit, backport-6, skip-changelog

#1802 More fstring cleanup
  changelogs/fragments/1802-flynt.yml
  docs/docsite/rst/dev_guidelines.rst
  plugins/modules/s3_object.py
  pyproject.toml
  tox.ini
Labels: mergeit

#1800 s3_object - remove docs for create/delete bucket.
  changelogs/fragments/1799-s3_object-bucket.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-6

#1813 s3_object - fix NoSuchTagSet error when S3 endpoint doesn't support tags
  changelogs/fragments/1607-NoSuchTagSet.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-6

#1801 Add example for deleting an existing VPC
  plugins/modules/ec2_vpc_net.py
Labels: mergeit, skip-changelog

#1650 ec2_instance: add AWSRetry.jittered_backoff on client.describe_instance_attribute
  changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
  plugins/modules/ec2_instance.py
Labels: bug, new_contributor, module, community_review, plugins, mergeit, backport-6

#1815 Update README with Ansible version 2.13 as the minimum supported version
  README.md
  changelogs/fragments/ansible_version_update.yml
  meta/runtime.yml
Labels: mergeit

#1809 Add rds_global_cluster_info module
  meta/runtime.yml
  plugins/modules/rds_global_cluster_info.py
  tests/integration/targets/rds_global_cluster_create/aliases
  tests/integration/targets/rds_global_cluster_create/defaults/main.yml
  tests/integration/targets/rds_global_cluster_create/tasks/main.yaml
Labels: mergeit, skip-changelog

#1823 Divide github workflows to maintain consistency across all repos
  .github/workflows/all_green_check.yml
  .github/workflows/changelog.yml
  .github/workflows/linters.yml
Labels: mergeit

#1822 Update README.md
  README.md
Labels: mergeit, skip-changelog

#1819 Revert pull request #1805 that migrated iam_server_certificate and the corresponding _info module
  changelogs/fragments/20231020-iam_server_certificate-revert.yml
  changelogs/fragments/migrate_iam_server_certificate.yml
  meta/runtime.yml
  plugins/modules/iam_server_certificate.py
  plugins/modules/iam_server_certificate_info.py
  tests/integration/targets/iam_server_certificate/aliases
  tests/integration/targets/iam_server_certificate/defaults/main.yml
  tests/integration/targets/iam_server_certificate/meta/main.yml
  tests/integration/targets/iam_server_certificate/tasks/generate-certs.yml
  tests/integration/targets/iam_server_certificate/tasks/main.yml
Labels: mergeit

#1826 Update main branch changelog after releasing 6.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1690-ec2_ami-add-support-org_arn-orgu_arn.yml
  changelogs/fragments/1714-parameters.yml
  changelogs/fragments/1767-elb_application_lb_info-Throttling.yml
  changelogs/fragments/20230906-galaxy.yml
  changelogs/fragments/20230908-alias-cleanup.yml
  changelogs/fragments/20230911-ec2_ami-release.yml
  changelogs/fragments/ec2_region.yml
Labels: mergeit, skip-changelog

#1723 ec2_import_image - new module
  meta/runtime.yml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_import_image.py
  plugins/modules/ec2_import_image_info.py
  tests/unit/plugins/modules/test_ec2_import_image.py
Labels: bug, new_plugin, new_module, module, plugins, mergeit, skip-changelog

#1833 Remove changelog from all_green workflow
  .github/workflows/all_green_check.yml
  .github/workflows/changelog.yml
Labels: mergeit

#1825 ec2_instance - add support for `placement` and `license_specifications`
  changelogs/fragments/1825-ec2_instances.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_license_specifications/aliases
  tests/integration/targets/ec2_instance_license_specifications/defaults/main.yml
  tests/integration/targets/ec2_instance_license_specifications/meta/main.yml
  tests/integration/targets/ec2_instance_license_specifications/tasks/main.yml
  tests/integration/targets/ec2_instance_placement_options/aliases
  tests/integration/targets/ec2_instance_placement_options/defaults/main.yml
  tests/integration/targets/ec2_instance_placement_options/meta/main.yml
  tests/integration/targets/ec2_instance_placement_options/tasks/main.yml
Labels: mergeit

#1786 Add ability to remove detached internet gateway
  changelogs/fragments/ec2_vpc_igw-delete_unattached-gateway.yml
  plugins/modules/ec2_vpc_igw.py
  tests/integration/targets/ec2_vpc_igw/defaults/main.yml
  tests/integration/targets/ec2_vpc_igw/tasks/main.yml
Labels: mergeit

#1838 Update docs links to use stable-7
  CI.md
  README.md
  docs/docsite/links.yml
  galaxy.yml
Labels: mergeit
