Repository ansible-collections/amazon.aws, pull requests merged in 2024-11, with the labels that each got.

#2380 Fix missing FQCN cloudwatch_metric_alarm
  changelogs/fragments/20241106-fqcn-cloudwatch-metric-alarm.yml
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
Labels: mergeit, backport-8, backport-9

#2384 Remove plugins/modules/ec2_vpc_peering.py from tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.18.txt
Labels: mergeit

#2372 rds_instance_pram_group_info: add new module rds_instance_pram_group_info
  meta/runtime.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_instance_param_group_info.py
  tests/integration/targets/rds_param_group/tasks/main.yml
Labels: mergeit, skip-changelog, backport-9

#2375 Ec2 transit gateway empty description
  changelogs/fragments/fix_tgw_description.yml
  plugins/modules/ec2_transit_gateway.py
Labels: mergeit, backport-9

#2383 Re-enable integration test for autoscaling_instance* modules
  changelogs/fragments/autoscaling_instance_enable_tests.yml
  tests/integration/targets/autoscaling_instance/aliases
  tests/integration/targets/autoscaling_instance/tasks/health.yml
Labels: mergeit, backport-9

#2386 lambda - Remove non-UTF-8 data from module output
  changelogs/fragments/2386-lambda-remove-non-utf-8-output.yml
  plugins/modules/lambda.py
Labels: mergeit

#2396 Deprecate managing instances through autoscaling_group
  changelogs/fragments/2396-autoscaling_groups-deprecations.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  plugins/modules/autoscaling_instance.py
  plugins/modules/autoscaling_instance_refresh.py
  plugins/modules/autoscaling_instance_refresh_info.py
Labels: mergeit, backport-9
