Repository ansible-collections/amazon.aws, pull requests merged in 2024-12, with the labels that each got.

#2406 ec2_key / setup_sshkey - fix integration tests (OpenSSH 9.5)
  changelogs/fragments/setup_sshkey.yml
  tests/integration/targets/ec2_key/tasks/main.yml
  tests/integration/targets/setup_sshkey/tasks/main.yml
Labels: mergeit, backport-9

#2398 Add instance tags to ec2_metadata_facts return values
  changelogs/fragments/20241120-ec2_metadata_facts-tags.yml
  plugins/modules/ec2_metadata_facts.py
  tests/integration/targets/ec2_metadata_facts/playbooks/setup.yml
  tests/integration/targets/ec2_metadata_facts/playbooks/test_metadata.yml
Labels: mergeit, backport-9

#2323 ec2_instance - Fix issue with launch template
  changelogs/fragments/20241004-ec2_instance-fix-issue-with-launch_template-when-there-no-default-subnet.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_launch_template/aliases
  tests/integration/targets/ec2_instance_launch_template/meta/main.yml
  tests/integration/targets/ec2_instance_launch_template/tasks/main.yml
Labels: mergeit

#2414 kms_key: integration test - Fetch updated state after pausing
  tests/integration/targets/kms_key/roles/kms_key/tasks/test_states.yml
Labels: mergeit, skip-changelog, backport-9

#2411 Prep amazon.aws 9.1.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241004-ec2_instance-fix-issue-with-launch_template-when-there-no-default-subnet.yml
  changelogs/fragments/20241106-fqcn-cloudwatch-metric-alarm.yml
  changelogs/fragments/20241120-ec2_metadata_facts-tags.yml
  changelogs/fragments/2377-fix-load-balancer-listener-comparison.yml
  changelogs/fragments/2396-autoscaling_groups-deprecations.yml
  changelogs/fragments/autoscaling_instance_enable_tests.yml
  changelogs/fragments/fix_tgw_description.yml
  changelogs/fragments/setup_sshkey.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2416 Update main branch after release 9.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241004-ec2_instance-fix-issue-with-launch_template-when-there-no-default-subnet.yml
  changelogs/fragments/20241106-fqcn-cloudwatch-metric-alarm.yml
  changelogs/fragments/20241120-ec2_metadata_facts-tags.yml
  changelogs/fragments/2377-fix-load-balancer-listener-comparison.yml
  changelogs/fragments/2396-autoscaling_groups-deprecations.yml
  changelogs/fragments/autoscaling_instance_enable_tests.yml
  changelogs/fragments/fix_tgw_description.yml
  changelogs/fragments/setup_sshkey.yml
Labels: mergeit

#2401 rds_cluster - fix issue when updating rds cluster domain
  changelogs/fragments/20241127-rds_cluster-fix-issue-occurring-when-updating-domain.yml
  plugins/modules/rds_cluster.py
  tests/unit/plugins/modules/test_rds_cluster.py
Labels: mergeit, backport-9

#2418 ec2_vpc_nat_gateway - catch extra error code for invalid elastic IP Id
  changelogs/fragments/20241206-ec2_nat_gateway-retry-on-invalid-elastic-ip-id.yaml
  plugins/module_utils/ec2.py
Labels: mergeit

#2391 cloudformation: Fix bug when updating stack's termination_protection with create_changeset set
  changelogs/fragments/2391-cloudformation-update-stack-termination_protection.yml
  plugins/modules/cloudformation.py
  tests/integration/targets/cloudformation/defaults/main.yml
  tests/integration/targets/cloudformation/tasks/main.yml
  tests/integration/targets/cloudformation/tasks/test_disable_rollback.yml
  tests/integration/targets/cloudformation/tasks/test_update_termination_protection.yml
Labels: mergeit, backport-9
