Repository ansible-collections/amazon.aws, pull requests merged in 2024-06, with the labels that each got.

#2083 backup_plan_info: bugfix to enable getting info of all backup plans
  changelogs/fragments/2083-backup_plan_info-bugfix-get-info-for-all-plans.yml
  plugins/modules/backup_plan_info.py
  tests/integration/targets/backup_plan/tasks/main.yml
Labels: mergeit, backport-7, backport-8

#2124 backup_plan: modify args spec and add examples for advanced_backup_settings parameter
  changelogs/fragments/fix_args_spec_supoptions.yml
  plugins/modules/backup_plan.py
Labels: mergeit, backport-7, backport-8

#2106 Update return block of Backup modules
  changelogs/fragments/update_return_block_backup_modules.yml
  plugins/modules/backup_plan.py
  plugins/modules/backup_plan_info.py
  plugins/modules/backup_selection.py
  plugins/modules/backup_vault.py
Labels: mergeit

#2131 Update changelog after release 7.6.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1979-do-not-ignore-ipv6-addresses.yaml
  changelogs/fragments/2083-backup_plan_info-bugfix-get-info-for-all-plans.yml
Labels: mergeit

#2050 Code refactoring - module_utils/elbv2
  .gitignore
  changelogs/fragments/20240417-refactor-module_utils-elbv2.yaml
  check_mypy.sh
  mypy.ini
  plugins/module_utils/elb_utils.py
  plugins/module_utils/elbv2.py
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  plugins/modules/elb_application_lb.py
  plugins/modules/elb_application_lb_info.py
  tests/unit/module_utils/elbv2/test_elbv2.py
  tests/unit/module_utils/elbv2/test_listener_rules.py
  tests/unit/module_utils/elbv2/test_prune.py
  tests/unit/module_utils/test_elbv2.py
Labels: mergeit

#2132 Update return block for lambda modules
  changelogs/fragments/update_return_block_lambda.yml
  plugins/modules/lambda_event.py
  plugins/modules/lambda_info.py
  plugins/modules/lambda_layer.py
  plugins/modules/lambda_policy.py
Labels: mergeit

#2119 Refactor rds instance
  changelogs/fragments/refactor_rds_instance.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_instance.py
  plugins/modules/rds_instance_info.py
  tests/unit/plugins/modules/test_rds_instance.py
  tests/unit/plugins/modules/test_rds_instance_info.py
Labels: mergeit

#2137 Update return block for route53_health_check
  changelogs/fragments/update_return_block_route53_health_check.yml
  plugins/modules/route53_health_check.py
Labels: mergeit

#2126 Update changelog after release 8.0.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2107-s3_download.yml
Labels: mergeit

#2086 [Part #4] Ensures the modules documentation follows the correct formats
  changelogs/fragments/documentation_update_4.yml
  plugins/modules/elb_application_lb.py
  plugins/modules/elb_application_lb_info.py
  plugins/modules/elb_classic_lb.py
  plugins/modules/iam_access_key.py
  plugins/modules/iam_access_key_info.py
  plugins/modules/iam_group.py
  plugins/modules/iam_instance_profile.py
  plugins/modules/iam_instance_profile_info.py
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_mfa_device_info.py
  plugins/modules/iam_password_policy.py
  plugins/modules/iam_policy.py
  plugins/modules/iam_policy_info.py
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  plugins/modules/iam_user.py
  plugins/modules/iam_user_info.py
Labels: mergeit

#2136 route53: Return diff only when module._diff is true
  changelogs/fragments/fix_module_diff_route53.yml
  plugins/modules/route53.py
  tests/integration/targets/route53/tasks/main.yml
Labels: mergeit

#2127 Update return block - aws_region_info, autoscaling_group_info, cloudformation
  changelogs/fragments/2127-update-return-block-aws_region_info-asg_info-cloudformation.yml
  plugins/modules/autoscaling_group_info.py
  plugins/modules/aws_region_info.py
  plugins/modules/cloudformation.py
Labels: mergeit

#2143 Fix back-ticks in changelogs
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, backport-8

#2141 Tests - Replace use of db.t2 instance class
  changelogs/fragments/2141-rds-t3-m4.yml
  plugins/modules/rds_instance.py
  plugins/modules/rds_instance_info.py
  tests/integration/targets/inventory_aws_rds/playbooks/tasks/rds_instance_create.yml
  tests/integration/targets/inventory_aws_rds/playbooks/test_inventory_with_hostvars_prefix_suffix.yml
  tests/integration/targets/rds_option_group/defaults/main.yml
Labels: mergeit, skip-changelog, backport-7, backport-8

#2135 Update return block - s3_bucket, s3_bucket_info, s3_object
  changelogs/fragments/2135-update-retrun-block-s3_bucket-s3_bucket_info-s3_object.yml
  plugins/modules/s3_bucket.py
  plugins/modules/s3_bucket_info.py
  plugins/modules/s3_object.py
Labels: mergeit

#2063 rds_cluster: add support for I/O-Optimized storage configuration for aurora clusters
  changelogs/fragments/2063-rds_cluster-add-support-io-optimized-storage-config.yml
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster_create/tasks/main.yaml
Labels: mergeit

#2144 Update return block - kms_key, kms_key_info
  changelogs/fragments/2144-update-retrun-block-kms_key-kms_key_info.yml
  plugins/modules/kms_key.py
  plugins/modules/kms_key_info.py
Labels: mergeit

#2150 Use double back-ticks instead of single ones
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, backport-8

#2087 [Part #5] Ensures the modules documentation follows the correct formats
  changelogs/fragments/documentation_update_5.yml
  plugins/modules/kms_key.py
  plugins/modules/kms_key_info.py
  plugins/modules/lambda.py
  plugins/modules/lambda_alias.py
  plugins/modules/lambda_event.py
  plugins/modules/lambda_execute.py
  plugins/modules/lambda_info.py
  plugins/modules/lambda_layer.py
  plugins/modules/lambda_layer_info.py
  plugins/modules/lambda_policy.py
  plugins/modules/route53.py
  plugins/modules/route53_health_check.py
  plugins/modules/route53_info.py
  plugins/modules/route53_zone.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_bucket_info.py
  plugins/modules/s3_object.py
  plugins/modules/s3_object_info.py
  plugins/modules/sts_assume_role.py
Labels: mergeit

#2046 s3_bucket transfer accleration
  changelogs/fragments/s3_bucket-accelerate_option.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/accelerate.yml
Labels: mergeit, backport-8

#2062 Add Object Lock default retention configuration for S3 buckets
  changelogs/fragments/s3_bucket-object-retention.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/default_retention.yml
Labels: mergeit, backport-8
