Repository ansible-collections/amazon.aws, pull requests merged in 2024-04, with the labels that each got.

#2030 Manual backport: Inventory plugins do not convert template parameters (#1980)
  plugins/plugin_utils/inventory.py
  tests/integration/targets/inventory_aws_ec2/playbooks/create_inventory_config.yml
  tests/integration/targets/inventory_aws_ec2/templates/config.ini.j2
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_template.yml.j2
  tests/unit/plugin_utils/inventory/test_inventory_base.py
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit, skip-changelog

#2029 Manual backport: Fix throttling issue when describing cloudwatch log groups (#2019)
  changelogs/fragments/20240314-cloudwatchlogs_log_group_info-fix-throttling-exceptions.yml
  plugins/modules/cloudwatchlogs_log_group_info.py
Labels: mergeit

#2033 [stable-7] fix docs test workflow
  .github/workflows/docs-pr.yml
Labels: backport-6

#2031 7.5.0 release prep
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2006-normalize-refactor.yml
  changelogs/fragments/20240314-cloudwatchlogs_log_group_info-fix-throttling-exceptions.yml
  changelogs/fragments/20240314-s3_object-copy-mode-with-metadata.yml
  changelogs/fragments/20240321-iam-user-info.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2032 Prep amazon.aws 6.5.4
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240314-cloudwatchlogs_log_group_info-fix-throttling-exceptions.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2036 Changelog update after 7.5.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1883-cloudwatchevent_rule-fix-json-input-handling-for-input_template.yml
  changelogs/fragments/2006-normalize-refactor.yml
  changelogs/fragments/20240124-module_utils-elbv2-fix-issue-with-authenticated-oidc.yml
  changelogs/fragments/20240212-lookup-secretsmanager_secret-fix-issue-when-nested-is-missing-and-on_missing-is-set-to-warn.yaml
  changelogs/fragments/20240227-fail_aws_error.yml
  changelogs/fragments/20240227-iam-refactor.yml
  changelogs/fragments/20240314-cloudwatchlogs_log_group_info-fix-throttling-exceptions.yml
  changelogs/fragments/20240314-s3_object-copy-mode-with-metadata.yml
  changelogs/fragments/20240321-iam-user-info.yml
Labels: mergeit

#2037 Changelog update after 6.5.4 release
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit

#2039 ec2_security_group - Use yield from in order to fix sanity errors
  changelogs/fragments/20240403-ec2_securty_group-sanity.yml
  plugins/modules/ec2_security_group.py
Labels: mergeit, backport-7

#2041 Drop support for ansible-core < 2.14
  README.md
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  meta/runtime.yml
Labels: mergeit, do_not_backport

#2048 Deprecate template parameter for cloudformation
  changelogs/fragments/cloudformation-template.yml
  plugins/modules/cloudformation.py
Labels: mergeit, backport-7

#2052 module_utils - Deprecation of sort_json_policy_dict (Fix sanity issue)
  changelogs/fragments/20240411-remove-deprecated-sort_json_policy_dict.yml
  plugins/module_utils/ec2.py
  plugins/module_utils/policy.py
  plugins/modules/ec2_vol.py
  tests/integration/targets/ec2_vol/tasks/main.yml
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/unit/module_utils/policy/test_sort_json_policy_dict.py
Labels: mergeit

#2040 Complete 8.0.0 deprecations and assign deprecations to release 9.0.0 instead of by date
  changelogs/fragments/8.0.0-deprecation-removal.yml
  plugins/inventory/aws_ec2.py
  plugins/module_utils/iam.py
  plugins/modules/iam_policy.py
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  plugins/modules/kms_key.py
  plugins/modules/kms_key_info.py
  tests/integration/targets/aws_region_info/tasks/main.yml
  tests/integration/targets/backup_selection/tasks/main.yml
  tests/integration/targets/cloudtrail/tasks/main.yml
  tests/integration/targets/ec2_instance_iam_instance_role/tasks/main.yml
  tests/integration/targets/iam_group/tasks/main.yml
  tests/integration/targets/iam_instance_profile/tasks/main.yml
  tests/integration/targets/iam_password_policy/tasks/main.yaml
  tests/integration/targets/iam_policy/tasks/main.yml
  tests/integration/targets/iam_role/tasks/boundary_policy.yml
  tests/integration/targets/iam_role/tasks/complex_role_creation.yml
  tests/integration/targets/iam_role/tasks/creation_deletion.yml
  tests/integration/targets/iam_role/tasks/description_update.yml
  tests/integration/targets/iam_role/tasks/inline_policy_update.yml
  tests/integration/targets/iam_role/tasks/main.yml
  tests/integration/targets/iam_role/tasks/max_session_update.yml
  tests/integration/targets/iam_role/tasks/parameter_checks.yml
  tests/integration/targets/iam_role/tasks/policy_update.yml
  tests/integration/targets/iam_role/tasks/role_removal.yml
  tests/integration/targets/iam_role/tasks/tags_update.yml
  tests/integration/targets/iam_user/tasks/main.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_inventory_ssm.yml
  tests/integration/targets/kms_key/roles/kms_key/tasks/test_grants.yml
  tests/integration/targets/kms_key/roles/kms_key/tasks/test_modify.yml
  tests/integration/targets/lambda/tasks/main.yml
  tests/integration/targets/lambda_alias/tasks/main.yml
  tests/integration/targets/lambda_event/tasks/setup.yml
  tests/integration/targets/lambda_event/tasks/teardown.yml
  tests/integration/targets/lambda_policy/tasks/main.yml
  tests/integration/targets/rds_instance_complex/tasks/main.yml
  tests/integration/targets/s3_bucket_info/tasks/main.yml
  tests/integration/targets/sts_assume_role/tasks/main.yml
  tests/sanity/ignore-2.17.txt
  tests/unit/module_utils/iam/test_iam_resource_transforms.py
Labels: mergeit, do_not_backport

#2047 Deprecate ignored boto3 parameters
  changelogs/fragments/sanity-boto3.yml
  plugins/module_utils/botocore.py
  plugins/module_utils/ec2.py
  plugins/module_utils/elbv2.py
  plugins/module_utils/modules.py
  plugins/modules/ec2_eni.py
  tests/unit/module_utils/modules/ansible_aws_module/test_passthrough.py
Labels: mergeit, backport-7

#2049 Clean up a range of small pylint warnings
  changelogs/fragments/sanity-simple.yml
  plugins/inventory/aws_ec2.py
  plugins/lookup/aws_collection_constants.py
  plugins/lookup/aws_service_ip_ranges.py
  plugins/lookup/secretsmanager_secret.py
  plugins/module_utils/acm.py
  plugins/module_utils/modules.py
  plugins/modules/autoscaling_group.py
  plugins/modules/cloudformation.py
  plugins/modules/ec2_eni.py
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_metadata_facts.py
  plugins/modules/ec2_security_group.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/elb_classic_lb.py
  plugins/modules/rds_cluster.py
  plugins/modules/rds_instance.py
  plugins/modules/rds_param_group.py
  plugins/modules/route53_health_check.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_object.py
  plugins/modules/s3_object_info.py
  tox.ini
Labels: mergeit

#2020 adding new modules to manage RDS cluster parameter groups
  meta/runtime.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_cluster_param_group.py
  plugins/modules/rds_cluster_param_group_info.py
  plugins/modules/rds_engine_versions_info.py
  plugins/modules/rds_instance_param_group.py
  tests/integration/targets/rds_cluster_param_group/aliases
  tests/integration/targets/rds_cluster_param_group/defaults/main.yaml
  tests/integration/targets/rds_cluster_param_group/tasks/main.yaml
Labels: mergeit, skip-changelog

#2057 s3_bucket: Refactor s3 bucket module
  changelogs/fragments/2057-s3_bucket-refactor.yml
  plugins/modules/s3_bucket.py
Labels: mergeit

#2026 add support for host option in placement.tenancy
  changelogs/fragments/2026-ec2_instance-add-support-for-placement-tenancy-host.yml
  plugins/modules/ec2_instance.py
Labels: mergeit, backport-7

#2066 iam_role_info - fix bug in prefix_path handling of missing /s
  changelogs/fragments/2065-iam_role_info.yml
  plugins/modules/iam_role_info.py
  tests/integration/targets/iam_role/defaults/main.yml
  tests/integration/targets/iam_role/tasks/creation_deletion.yml
Labels: mergeit, backport-7
