Repository ansible-collections/amazon.aws, pull requests merged in 2024-02, with the labels that each got.

#1961 backup_plan - fix idempotency issue with botocore >= 1.31.36
  changelogs/fragments/20240202-backup_plan-idempotency.yml
  plugins/modules/backup_plan.py
  tests/integration/targets/backup_plan/meta/main.yml
  tests/integration/targets/backup_plan/tasks/main.yml
Labels: mergeit, backport-7

#1963 Prep amazon.aws 7.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1839-rds_cluster-add-support-for-serverless_v2_scaling_configuration.yml
  changelogs/fragments/1939-image_uri.yml
  changelogs/fragments/1951-error-handler.yml
  changelogs/fragments/20231211-s3_bucket_info-add-support-for-bucket_versioning.yml
  changelogs/fragments/20240129-aws_ec2-inventory-bugfix.yml
  changelogs/fragments/20240202-backup_plan-idempotency.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1964 Prep amazon.aws 6.5.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240129-aws_ec2-inventory-bugfix.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1967 Add the release_summary accidentally removed when prepping 7.3.0
  changelogs/changelog.yaml
Labels: mergeit

#1966 Update main changelog after 6.5.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240129-aws_ec2-inventory-bugfix.yml
Labels: mergeit

#1965 Changelog update after release 7.3.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1839-rds_cluster-add-support-for-serverless_v2_scaling_configuration.yml
  changelogs/fragments/1939-image_uri.yml
  changelogs/fragments/1951-error-handler.yml
  changelogs/fragments/20231211-s3_bucket_info-add-support-for-bucket_versioning.yml
  changelogs/fragments/20240202-backup_plan-idempotency.yml
Labels: mergeit

#1917 rds_instance - Allow empty enable_cloudwatch_logs_exports
  changelogs/fragments/20231211-rds_instance_cloudwatch.yml
  plugins/modules/rds_instance.py
  tests/integration/targets/rds_instance_modify/tasks/main.yml
Labels: mergeit

#1973 Remove redundant workflows
  .github/workflows/tests.yml
  changelogs/fragments/remove_rendundant_workflow.yml
Labels: mergeit

#1972 lookup/secretsmanager_secret - fix issue with missing nested secret and on_missing=warn
  changelogs/fragments/20240212-lookup-secretsmanager_secret-fix-issue-when-nested-is-missing-and-on_missing-is-set-to-warn.yaml
  plugins/lookup/secretsmanager_secret.py
  tests/integration/targets/lookup_secretsmanager_secret/defaults/main.yml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/main.yaml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/nested.yaml
  tests/unit/plugins/lookup/test_secretsmanager_secret.py
Labels: mergeit, backport-6, backport-7

#1970 [lambda_event] Fix issue when function name is specified and user is using AWS SSO
  changelogs/fragments/20240208-lambda_event-fix-validate-params.yml
  plugins/modules/lambda_event.py
  tests/unit/plugins/modules/test_lambda_event.py
Labels: mergeit

#1984 Fix unsafe conditional
  tests/integration/targets/ec2_instance_state_config_updates/tasks/main.yml
Labels: mergeit, backport-6, backport-7

#1993 Minor flynt fix
  .github/workflows/docs-pr.yml
  plugins/modules/lambda_event.py
  tox.ini
Labels: mergeit, skip-changelog, backport-7

#1992 Remove unneeded sanity ignore for ansible 2.17
  tests/sanity/ignore-2.17.txt
Labels: mergeit, backport-7

#1996 Remove unused code
  changelogs/fragments/20240227-zombies.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/cloudtrail.py
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_vol.py
  plugins/modules/elb_classic_lb.py
  plugins/modules/kms_key.py
  plugins/modules/s3_object.py
Labels: mergeit

#1997 Add fail method that knows how to handle AnsibleAWSErrors
  changelogs/fragments/20240227-fail_aws_error.yml
  plugins/module_utils/modules.py
Labels: mergeit, backport-7

#1998 Big IAM code refactor
  changelogs/fragments/20240227-iam-refactor.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_access_key.py
  plugins/modules/iam_access_key_info.py
  plugins/modules/iam_group.py
  plugins/modules/iam_instance_profile.py
  plugins/modules/iam_instance_profile_info.py
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_mfa_device_info.py
  plugins/modules/iam_role.py
  plugins/modules/iam_role_info.py
  plugins/modules/iam_user.py
  plugins/modules/iam_user_info.py
  tests/integration/targets/iam_access_key/tasks/main.yml
  tests/integration/targets/iam_group/tasks/users.yml
Labels: mergeit, backport-7
