Repository ansible-collections/amazon.aws, pull requests merged in 2024-10, with the labels that each got.

#2302 added some shared code into module_utils/ec2
  changelogs/fragments/20240924-module_utils-ec2.yml
  plugins/module_utils/ec2.py
Labels: mergeit

#2316 Fix unit tests under Python 3.13
  tests/unit/constraints.txt
Labels: mergeit, backport-8

#2303 Add utils for ec_vpc_peer* modules
  changelogs/fragments/20240924-ec2-utils.yml
  plugins/module_utils/ec2.py
Labels: mergeit

#2315 DNM Migrate elb_classic_lb_info* modules and tests
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  meta/runtime.yml
  plugins/modules/elb_classic_lb_info.py
  tests/integration/targets/elb_classic_lb/tasks/basic_internal.yml
  tests/integration/targets/elb_classic_lb/tasks/basic_public.yml
  tests/integration/targets/elb_classic_lb_info/aliases
  tests/integration/targets/elb_classic_lb_info/defaults/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
Labels: mergeit

#2317 Add BaseWaiterFactory, so we can start splitting the waiters
  plugins/module_utils/waiter.py
  tests/unit/module_utils/waiter/test_custom_waiter_config.py
  tests/unit/plugins/modules/test_s3_object.py
Labels: mergeit

#2329 Update README
  README.md
Labels: mergeit, skip-changelog, backport-8

#2161 [9.0.0] Bump botocore/boto3 requirements (add deprecation reminder about Python 3.8 support)
  README.md
  changelogs/fragments/botocore-python.yaml
  plugins/module_utils/botocore.py
  plugins/modules/rds_instance.py
  requirements.txt
  tests/integration/constraints.txt
  tests/integration/targets/ec2_eni/tasks/test_modifying_delete_on_termination.yaml
  tests/integration/targets/rds_instance_modify/meta/main.yml
  tests/integration/targets/rds_instance_modify/tasks/main.yml
  tests/unit/constraints.txt
  tests/unit/module_utils/modules/ansible_aws_module/test_minimal_versions.py
Labels: mergeit

#2326 Revert "DNM Migrate elb_classic_lb_info* modules and tests"
  changelogs/fragments/migrate_elb_classic_lb_info.yml
  meta/runtime.yml
  plugins/modules/elb_classic_lb_info.py
  tests/integration/targets/elb_classic_lb/tasks/basic_internal.yml
  tests/integration/targets/elb_classic_lb/tasks/basic_public.yml
  tests/integration/targets/elb_classic_lb_info/aliases
  tests/integration/targets/elb_classic_lb_info/defaults/main.yml
  tests/integration/targets/elb_classic_lb_info/tasks/main.yml
Labels: mergeit

#2322 Add utils for ec2_placement_group
  changelogs/fragments/add_utils_ec2_placement_group.yml
  plugins/module_utils/ec2.py
  tests/integration/targets/ec2_instance_placement_options/aliases
Labels: mergeit

#2312 module_utils/ec2 - Add utils for the ec2_vpc_vpn* modules
  changelogs/fragments/20240927-ec2-utils.yml
  plugins/module_utils/ec2.py
Labels: mergeit

#2306 Corrected spelling of word
  plugins/modules/ec2_instance.py
Labels: mergeit, skip-changelog, backport-8

#2314 Add module_util support for transit gateway vpc attachment module
  changelogs/fragments/add_support_tgw_vpc.yml
  plugins/module_utils/ec2.py
  plugins/module_utils/waiters.py
Labels: mergeit

#2353 Use ansible-ref: devel for docs build workflows
  .github/workflows/docs-pr.yml
  .github/workflows/docs-push.yml
Labels: mergeit

#2286 cloudwatchlogs_log_group_metric_filter: add support for unit and dimensions
  changelogs/fragments/20240906-cloudwatch-log-metric-filter-unit-dimensions.yml
  plugins/modules/cloudwatchlogs_log_group_metric_filter.py
  tests/integration/targets/cloudwatchlogs/tasks/cloudwatchlogs_tests.yml
Labels: mergeit, backport-8

#2296 New module - autoscaling_instance(_info)
  meta/runtime.yml
  plugins/module_utils/_autoscaling/__init__.py
  plugins/module_utils/_autoscaling/common.py
  plugins/module_utils/_autoscaling/groups.py
  plugins/module_utils/_autoscaling/instances.py
  plugins/module_utils/_autoscaling/transformations.py
  plugins/module_utils/_autoscaling/waiters.py
  plugins/module_utils/autoscaling.py
  plugins/modules/autoscaling_instance.py
  plugins/modules/autoscaling_instance_info.py
  tests/integration/targets/autoscaling_instance/aliases
  tests/integration/targets/autoscaling_instance/defaults/main.yml
  tests/integration/targets/autoscaling_instance/files/user_data
  tests/integration/targets/autoscaling_instance/meta/main.yml
  tests/integration/targets/autoscaling_instance/tasks/attach_detach.yml
  tests/integration/targets/autoscaling_instance/tasks/describe.yml
  tests/integration/targets/autoscaling_instance/tasks/env_cleanup.yml
  tests/integration/targets/autoscaling_instance/tasks/env_setup.yml
  tests/integration/targets/autoscaling_instance/tasks/health.yml
  tests/integration/targets/autoscaling_instance/tasks/main.yml
  tests/integration/targets/autoscaling_instance/tasks/protection.yml
  tests/integration/targets/autoscaling_instance/tasks/tests.yml
  tests/integration/targets/autoscaling_instance/tmp/inventory
  tests/integration/targets/autoscaling_instance/tmp/main.yml
  tests/integration/targets/autoscaling_instance/tmp/runme.sh
  tests/integration/targets/setup_ec2_vpc/tasks/cleanup.yml
  tests/unit/module_utils/autoscaling/test_autoscaling_error_handler.py
  tests/unit/module_utils/autoscaling/test_autoscaling_resource_transforms.py
  tox.ini
Labels: mergeit, skip-changelog

#2359 ec2_vpc_peering_info - Deprecate result returned key
  changelogs/fragments/20241024-ec2_vpc_peering_info.yml
  plugins/modules/ec2_vpc_peering_info.py
Labels: mergeit

#2358 Rename ec2_vpc_peer to ec2_vpc_peering
  changelogs/fragments/20241024-ec2_vpc_peer-rename.yml
  meta/runtime.yml
  plugins/modules/ec2_vpc_peering.py
  tests/integration/targets/ec2_security_group/tasks/multi_account.yml
  tests/integration/targets/ec2_vpc_peering/aliases
  tests/integration/targets/ec2_vpc_peering/defaults/main.yml
  tests/integration/targets/ec2_vpc_peering/meta/main.yml
  tests/integration/targets/ec2_vpc_peering/tasks/main.yml
  tests/sanity/ignore-2.18.txt
Labels: mergeit

#2133 fix(ec2_vol): output volume informations when volume exists in check mode
  changelogs/fragments/202401025-ec2_vol.yml
  plugins/modules/ec2_vol.py
Labels: mergeit

#2354 Fix `rds_snapshot_info` return values in docs
  plugins/modules/rds_snapshot_info.py
Labels: mergeit

#2365 Links update after branching stable-9
  CI.md
  README.md
  changelogs/fragments/20241029-update-docs.yml
  docs/docsite/links.yml
Labels: mergeit

#2366 Bump release for main branch to 10.0.0-dev0
  changelogs/fragments/20241029-main-10.0.0.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit
