Repository ansible-collections/amazon.aws, pull requests merged in 2024-08, with the labels that each got.

#2209 Add option "metadata_token_ttl_seconds" to ec2_metadata_facts module.
  changelogs/fragments/2209-ec2_metadata_facts-add-configurable-ttl-parameter.yml
  plugins/modules/ec2_metadata_facts.py
  tests/integration/targets/ec2_metadata_facts/playbooks/test_metadata.yml
Labels: mergeit, backport-8

#2213 README: Add Communication section with Forum information
  README.md
Labels: mergeit

#2221 iam_role - Deprecate creating/deleting instance profiles through iam_role
  changelogs/fragments/20240820-iam_role-profiles.yml
  plugins/modules/iam_role.py
Labels: mergeit, backport-8

#2222 s3_bucket - remove default for accelerate_enabled
  changelogs/fragments/2220-accelerate_enabled-unsupported.yml
  plugins/modules/s3_bucket.py
Labels: mergeit, backport-8

#2219 Fix performance_insights_kms_key_id snake case variation
  changelogs/fragments/20240810-rds_instance-performance_insights_kms_key_id.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_instance.py
Labels: mergeit, backport-8

#1730 Include an example for listing all Lambdas in any region
  plugins/modules/lambda_info.py
Labels: docs, mergeit, skip-changelog

#2236 [PR #2135 backport][stable-8] Update return block - s3_bucket, s3_bucket_info, s3_object
  changelogs/fragments/2135-update-retrun-block-s3_bucket-s3_bucket_info-s3_object.yml
  plugins/modules/s3_bucket.py
  plugins/modules/s3_bucket_info.py
  plugins/modules/s3_object.py
Labels: mergeit

#1728 Included example to use termination_protection for ec2 deployment
  plugins/modules/ec2_instance.py
Labels: docs, mergeit

#2206 s3_object - Add support for expcted_bucket_owner option
  changelogs/fragments/20240730-s3_object-expected-bucket-owner.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-8

#2215 rds_cluster: state change fix
  changelogs/fragments/2214-rds_cluster-limit-params-sent-to-api-for-states.yml
  plugins/modules/rds_cluster.py
  tests/integration/targets/rds_cluster_states/tasks/main.yml
Labels: mergeit, backport-8

#2253 ec2_ami: add support for uefi-preferred boot mode
  changelogs/fragments/2253-ec2_ami-add-support-uefi-preferred-boot-mode.yml
  plugins/modules/ec2_ami.py
Labels: mergeit, backport-8

#2196 module cloudwatch_metric_alarm support DatapointsToAlarm config
  changelogs/fragments/2196-cloudwatch_metric_alarm_support-DatapointsToAlarm-config.yml
  plugins/modules/cloudwatch_metric_alarm.py
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
Labels: mergeit, backport-8

#1865 cloudwatch_metric_alarm: fix idempotency for alarm without dimensions
  changelogs/fragments/20240216-cloudwatch-metric-alarm-idempotency.yml
  plugins/modules/cloudwatch_metric_alarm.py
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
Labels: mergeit, backport-8

#2245 linting in examples
  plugins/modules/ec2_instance.py
  plugins/modules/lambda_info.py
  plugins/modules/rds_instance.py
Labels: mergeit, skip-changelog

#2251 [PR #2219 backport][stable-8] Fix performance_insights_kms_key_id snake case variation
  changelogs/fragments/20240810-rds_instance-performance_insights_kms_key_id.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_instance.py
Labels: mergeit

#2263 Tweak 'version_added' information for PRs based on actual backport dates
  plugins/modules/cloudwatch_metric_alarm.py
  plugins/modules/ec2_instance.py
  plugins/modules/rds_cluster.py
Labels: mergeit, skip-changelog, backport-8

#2268 Make the ami pattern generic to avoid searching for deprecated amis
  changelogs/fragments/fix_deperecated_ami.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/test_inventory_ssm.yml
  tests/integration/targets/inventory_aws_ec2/tasks/setup.yml
Labels: mergeit, backport-8

#1756 Create droppath option in ssm_parameter.py
  changelogs/fragments/add-droppath-option-to-ssm-lookup.yml
  plugins/lookup/ssm_parameter.py
  tests/integration/targets/lookup_ssm_parameter/tasks/main.yml
Labels: mergeit, backport-8

#1659 Fix ec2_instance 'state' processing when exact_count is used
  changelogs/fragments/1659-ec2_instance-ensure-state-exact_count.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_instance_multiple/tasks/main.yml
Labels: bug, new_contributor, module, community_review, plugins, small_patch, mergeit, backport-8
