Repository ansible-collections/amazon.aws, pull requests merged in 2024-07, with the labels that each got.

#2123 ec2_instance - update network interface parameters
  changelogs/fragments/20240604-ec2_instance-refactor-network-option.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_eni/tasks/main.yaml
  tests/integration/targets/ec2_instance_external_resource_attach/tasks/main.yml
  tests/integration/targets/ec2_instance_network/aliases
  tests/integration/targets/ec2_instance_network/defaults/main.yml
  tests/integration/targets/ec2_instance_network/meta/main.yml
  tests/integration/targets/ec2_instance_network/tasks/enis.yml
  tests/integration/targets/ec2_instance_network/tasks/failures.yml
  tests/integration/targets/ec2_instance_network/tasks/main.yml
  tests/integration/targets/ec2_instance_placement_options/tasks/main.yml
  tests/integration/targets/ec2_instance_tags_and_vpc_settings/tasks/main.yml
  tests/integration/targets/ec2_metadata_facts/playbooks/setup.yml
  tests/integration/targets/ec2_metadata_facts/templates/inventory.j2
  tests/integration/targets/setup_ec2_instance_env/tasks/main.yml
Labels: mergeit

#2154 [Manual backport] s3_bucket transfer accleration (#2046)
  changelogs/fragments/s3_bucket-accelerate_option.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/accelerate.yml
Labels: mergeit

#2155 Adjust docs publish workflow
  .github/workflows/docs-push.yml
Labels: backport-3, mergeit, backport-4, backport-5, backport-6, backport-7, backport-8

#2156 Update return block documentation for rds modules
  changelogs/fragments/update_return_block_rds.yml
  plugins/modules/rds_cluster.py
  plugins/modules/rds_cluster_info.py
  plugins/modules/rds_cluster_param_group.py
  plugins/modules/rds_cluster_snapshot.py
  plugins/modules/rds_global_cluster_info.py
  plugins/modules/rds_option_group_info.py
  plugins/modules/rds_snapshot_info.py
Labels: mergeit

#2177 [manual backport] Add Object Lock default retention configuration for S3 buckets (#2062)
  changelogs/fragments/s3_bucket-object-retention.yml
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/inventory
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/default_retention.yml
Labels: mergeit

#2178 Prep amazon.aws 8.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2141-rds-t3-m4.yml
  changelogs/fragments/fix_args_spec_supoptions.yml
  changelogs/fragments/s3_bucket-accelerate_option.yml
  changelogs/fragments/s3_bucket-object-retention.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2179 Changelog update after release 8.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2141-rds-t3-m4.yml
  changelogs/fragments/fix_args_spec_supoptions.yml
  changelogs/fragments/s3_bucket-accelerate_option.yml
  changelogs/fragments/s3_bucket-object-retention.yml
Labels: mergeit

#2163 Refactor aws_az_region_info* modules
  changelogs/fragments/20240107-refactor_aws_az_region_info-modules.yml
  plugins/module_utils/transformation.py
  plugins/modules/aws_az_info.py
  plugins/modules/aws_region_info.py
  tests/integration/targets/ec2_instance_placement_options/tasks/main.yml
  tests/integration/targets/ec2_instance_placement_options/tasks/select_availability_zone.yml
  tests/unit/module_utils/transformation/test_sanitize_filters_to_boto3_filter_list.py
Labels: mergeit

#2168 Refactor ec2_key* modules
  changelogs/fragments/20240107-refactor_ec2_key-modules.yml
  plugins/modules/ec2_key.py
  plugins/modules/ec2_key_info.py
  tests/unit/plugins/modules/test_ec2_key.py
Labels: mergeit

#2164 Refactor ec2_ami* modules
  changelogs/fragments/20240107-refactor_ec2_ami-modules.yml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_ami_info.py
  tests/unit/plugins/modules/test_ec2_ami.py
  tests/unit/plugins/modules/test_ec2_ami_info.py
Labels: mergeit

#2169 Refactor ec2_security* modules
  changelogs/fragments/20240107-refactor_ec2_security-modules.yml
  plugins/module_utils/transformation.py
  plugins/modules/ec2_security_group.py
  plugins/modules/ec2_security_group_info.py
  tests/integration/targets/ec2_security_group/aliases
  tests/integration/targets/ec2_security_group/tasks/rule_group_create.yml
Labels: mergeit

#2167 Refactor ec2_import_image* modules
  changelogs/fragments/20240107-refactor_ec2_import_image-modules.yml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_import_image.py
  plugins/modules/ec2_import_image_info.py
  tests/unit/plugins/modules/test_ec2_import_image.py
Labels: mergeit

#2170 Refactor ec2_vol* modules
  changelogs/fragments/20240107-refactor_ec2_vol-modules.yml
  plugins/modules/ec2_vol.py
  plugins/modules/ec2_vol_info.py
Labels: mergeit

#2160 Refactor ec2_vpc_subnet* modules
  changelogs/fragments/20240701-refactor_ec2_vpc_subnet-modules.yml
  plugins/modules/ec2_vpc_subnet.py
  plugins/modules/ec2_vpc_subnet_info.py
Labels: mergeit

#2185 Add 'alternative' for EC2_REGION deprecation for non-module plugins
  plugins/doc_fragments/region.py
Labels: mergeit, backport-7, backport-8

#2182 Integration tests - Delete instances created into default VPC
  changelogs/fragments/20240703-integration-tests-delete-instances.yml
  tests/integration/targets/ec2_instance_info/tasks/main.yml
  tests/integration/targets/ec2_instance_metadata_options/tasks/main.yml
Labels: mergeit

#2166 Refactor ec2_eni* modules
  changelogs/fragments/20240107-refactor_ec2_eni-modules.yml
  plugins/modules/ec2_eni.py
  plugins/modules/ec2_eni_info.py
  tests/integration/targets/ec2_eni/aliases
  tests/integration/targets/ec2_eni/tasks/test_create_attached_multiple.yml
  tests/unit/plugins/modules/test_ec2_eni_info.py
Labels: mergeit

#2188 Switch from t3.micro to t3a.micro in some of the integration tests
  changelogs/fragments/use_t3a_micro_in_tests.yml
  tests/integration/targets/ec2_instance_instance_minimal/defaults/main.yml
  tests/integration/targets/ec2_instance_instance_multiple/defaults/main.yml
  tests/integration/targets/ec2_instance_instance_no_wait/defaults/main.yml
  tests/integration/targets/ec2_instance_license_specifications/defaults/main.yml
  tests/integration/targets/ec2_instance_metadata_options/defaults/main.yml
  tests/integration/targets/ec2_instance_security_group/defaults/main.yml
  tests/integration/targets/ec2_instance_state_config_updates/defaults/main.yml
  tests/integration/targets/ec2_instance_tags_and_vpc_settings/defaults/main.yml
  tests/integration/targets/ec2_instance_termination_protection/defaults/main.yml
  tests/integration/targets/ec2_instance_uptime/defaults/main.yml
Labels: mergeit, backport-7, backport-8

#2191 Ensure placement group is deleted
  tests/integration/targets/ec2_instance_placement_options/tasks/main.yml
Labels: mergeit, skip-changelog, backport-7, backport-8

#2165 Refactor ec2_eip* modules
  changelogs/fragments/20240107-refactor_ec2_eip-modules.yml
  plugins/modules/ec2_eip.py
  plugins/modules/ec2_eip_info.py
  tests/integration/targets/ec2_eip/aliases
  tests/integration/targets/ec2_eip/tasks/allocate.yml
  tests/integration/targets/ec2_eip/tasks/attach_detach_to_eni.yml
  tests/integration/targets/ec2_eip/tasks/attach_detach_to_instance.yml
  tests/integration/targets/ec2_eip/tasks/main.yml
  tests/integration/targets/ec2_eip/tasks/release.yml
  tests/integration/targets/ec2_eip/tasks/reuse_with_tag.yml
  tests/integration/targets/ec2_eip/tasks/setup.yml
  tests/integration/targets/ec2_eip/tasks/tagging.yml
  tests/integration/targets/ec2_eip/tasks/teardown.yml
  tests/unit/plugins/modules/ec2_eip/test_check_is_instance.py
  tests/unit/plugins/modules/ec2_eip/test_generate_tag_dict.py
Labels: mergeit

#2157 Rework of client creation error handling.
  changelogs/fragments/20240628-boto3_conn.yml
  plugins/module_utils/botocore.py
  plugins/module_utils/modules.py
  plugins/plugin_utils/base.py
  plugins/plugin_utils/botocore.py
  tests/unit/module_utils/botocore/test_aws_region.py
  tests/unit/module_utils/botocore/test_boto3_conn.py
  tests/unit/plugin_utils/botocore/test_boto3_conn_plugin.py
Labels: mergeit, do_not_backport

#2195 Update return block - iam_* modules
  changelogs/fragments/2195-update-return-block-iam-modules.yml
  plugins/modules/iam_instance_profile_info.py
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_policy.py
  plugins/modules/iam_policy_info.py
  plugins/modules/iam_role.py
  plugins/modules/iam_user.py
  plugins/modules/iam_user_info.py
Labels: mergeit

#2151 elb_* - Update RETURN block docs
  changelogs/fragments/elb_docs_update.yml
  plugins/modules/elb_application_lb.py
  plugins/modules/elb_application_lb_info.py
  plugins/modules/elb_classic_lb.py
Labels: mergeit

#2198 Integration/ec2_eip - add tags to EIP
  changelogs/fragments/20240718-integration-ec2_eip.yaml
  tests/integration/targets/ec2_eip/defaults/main.yml
  tests/integration/targets/ec2_eip/tasks/allocate.yml
  tests/integration/targets/ec2_eip/tasks/attach_detach_to_eni.yml
  tests/integration/targets/ec2_eip/tasks/attach_detach_to_instance.yml
  tests/integration/targets/ec2_eip/tasks/common.yml
  tests/integration/targets/ec2_eip/tasks/release.yml
  tests/integration/targets/ec2_eip/tasks/reuse_with_tag.yml
  tests/integration/targets/ec2_eip/tasks/setup.yml
  tests/integration/targets/ec2_eip/tasks/tagging.yml
  tests/integration/targets/ec2_eip/templates/tag.yaml.j2
Labels: mergeit

#2192 Refactor ec2_instance and ec2_instance_info modules
  changelogs/fragments/20240712-refactor-ec2_instance-modules.yaml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_instance_info.py
  tests/integration/targets/ec2_instance_network/tasks/enis.yml
  tests/unit/plugins/modules/ec2_instance/test_build_run_instance_spec.py
  tests/unit/plugins/modules/ec2_instance/test_determine_iam_role.py
Labels: mergeit

#2200 Update Readme to match the template
  README.md
  changelogs/fragments/readme_template_update.yml
Labels: mergeit

#2194 s3_bucket - fix transfer acceleration issue with AWS GovCloud
  changelogs/fragments/20240715-s3_bucket-transfer-accelerate.yaml
  plugins/modules/s3_bucket.py
  tests/unit/plugins/modules/s3_bucket/__init__.py
  tests/unit/plugins/modules/s3_bucket/test_handle_bucket_accelerate.py
Labels: mergeit

#2138 Refactor rds snapshot modules
  changelogs/fragments/refactor_rds_snapshot_modules.yml
  plugins/module_utils/rds.py
  plugins/modules/rds_cluster_snapshot.py
  plugins/modules/rds_instance.py
  plugins/modules/rds_instance_snapshot.py
  plugins/modules/rds_snapshot_info.py
  tests/unit/module_utils/test_rds.py
  tests/unit/plugins/modules/test_rds_instance.py
Labels: mergeit

#2201 Bump the ansible-lint version to 24.7.0
  changelogs/fragments/2201-bump-ansible-lint-version.yml
  tox.ini
Labels: mergeit
