Repository ansible-collections/amazon.aws, pull requests merged in 2024-09, with the labels that each got.

#2276 [PR #1659/26d7243 backport][stable-8] Fix ec2_instance 'state' processing when exact_count is used
  changelogs/fragments/1659-ec2_instance-ensure-state-exact_count.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_instance_multiple/tasks/main.yml
Labels: mergeit

#2277 Prep amazon.aws 8.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1659-ec2_instance-ensure-state-exact_count.yml
  changelogs/fragments/20240216-cloudwatch-metric-alarm-idempotency.yml
  changelogs/fragments/20240604-ec2_instance-refactor-network-option.yml
  changelogs/fragments/20240703-integration-tests-delete-instances.yml
  changelogs/fragments/20240715-s3_bucket-transfer-accelerate.yaml
  changelogs/fragments/20240730-s3_object-expected-bucket-owner.yml
  changelogs/fragments/20240810-rds_instance-performance_insights_kms_key_id.yml
  changelogs/fragments/20240820-iam_role-profiles.yml
  changelogs/fragments/20240824-s3_bucket-unpack.yml
  changelogs/fragments/2063-rds_cluster-add-support-io-optimized-storage-config.yml
  changelogs/fragments/2074-s3_bucket-inventory-feature.yml
  changelogs/fragments/2127-update-return-block-aws_region_info-asg_info-cloudformation.yml
  changelogs/fragments/2135-update-retrun-block-s3_bucket-s3_bucket_info-s3_object.yml
  changelogs/fragments/2144-update-retrun-block-kms_key-kms_key_info.yml
  changelogs/fragments/2195-update-return-block-iam-modules.yml
  changelogs/fragments/2196-cloudwatch_metric_alarm_support-DatapointsToAlarm-config.yml
  changelogs/fragments/2209-ec2_metadata_facts-add-configurable-ttl-parameter.yml
  changelogs/fragments/2214-rds_cluster-limit-params-sent-to-api-for-states.yml
  changelogs/fragments/2220-accelerate_enabled-unsupported.yml
  changelogs/fragments/2253-ec2_ami-add-support-uefi-preferred-boot-mode.yml
  changelogs/fragments/2266-acceleration-eu_north_1.yml
  changelogs/fragments/add-droppath-option-to-ssm-lookup.yml
  changelogs/fragments/add_evaluate_low_sample_count_percentile.yml
  changelogs/fragments/documentation_update.yml
  changelogs/fragments/documentation_update_2.yml
  changelogs/fragments/documentation_update_3.yml
  changelogs/fragments/documentation_update_4.yml
  changelogs/fragments/documentation_update_5.yml
  changelogs/fragments/documentation_update_6.yml
  changelogs/fragments/elb_docs_update.yml
  changelogs/fragments/fix_deperecated_ami.yml
  changelogs/fragments/fix_module_diff_route53.yml
  changelogs/fragments/update_return_block_backup_modules.yml
  changelogs/fragments/update_return_block_cloud_modules.yml
  changelogs/fragments/update_return_block_ec2_2.yml
  changelogs/fragments/update_return_block_lambda.yml
  changelogs/fragments/update_return_block_rds.yml
  changelogs/fragments/update_return_block_route53_health_check.yml
  changelogs/fragments/use_t3a_micro_in_tests.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2282 iam_role - makes EntityAlreadyExists error a warning and fixes bug when not creating a profile
  changelogs/fragments/2281-iam_role-support-not-creating.yml
  plugins/modules/iam_role.py
  tests/integration/targets/iam_role/tasks/instance_profile.yml
  tests/integration/targets/iam_role/tasks/main.yml
Labels: mergeit, backport-8

#2284 Prep amazon.aws 8.2.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2281-iam_role-support-not-creating.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2279 Update main branch after releasing amazon.aws 8.2.0 and 8.2.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1659-ec2_instance-ensure-state-exact_count.yml
  changelogs/fragments/20240216-cloudwatch-metric-alarm-idempotency.yml
  changelogs/fragments/20240604-ec2_instance-refactor-network-option.yml
  changelogs/fragments/20240703-integration-tests-delete-instances.yml
  changelogs/fragments/20240715-s3_bucket-transfer-accelerate.yaml
  changelogs/fragments/20240730-s3_object-expected-bucket-owner.yml
  changelogs/fragments/20240810-rds_instance-performance_insights_kms_key_id.yml
  changelogs/fragments/20240820-iam_role-profiles.yml
  changelogs/fragments/20240824-s3_bucket-unpack.yml
  changelogs/fragments/2063-rds_cluster-add-support-io-optimized-storage-config.yml
  changelogs/fragments/2074-s3_bucket-inventory-feature.yml
  changelogs/fragments/2127-update-return-block-aws_region_info-asg_info-cloudformation.yml
  changelogs/fragments/2135-update-retrun-block-s3_bucket-s3_bucket_info-s3_object.yml
  changelogs/fragments/2144-update-retrun-block-kms_key-kms_key_info.yml
  changelogs/fragments/2195-update-return-block-iam-modules.yml
  changelogs/fragments/2196-cloudwatch_metric_alarm_support-DatapointsToAlarm-config.yml
  changelogs/fragments/2209-ec2_metadata_facts-add-configurable-ttl-parameter.yml
  changelogs/fragments/2214-rds_cluster-limit-params-sent-to-api-for-states.yml
  changelogs/fragments/2220-accelerate_enabled-unsupported.yml
  changelogs/fragments/2253-ec2_ami-add-support-uefi-preferred-boot-mode.yml
  changelogs/fragments/2266-acceleration-eu_north_1.yml
  changelogs/fragments/2281-iam_role-support-not-creating.yml
  changelogs/fragments/add-droppath-option-to-ssm-lookup.yml
  changelogs/fragments/add_evaluate_low_sample_count_percentile.yml
  changelogs/fragments/documentation_update.yml
  changelogs/fragments/documentation_update_2.yml
  changelogs/fragments/documentation_update_3.yml
  changelogs/fragments/documentation_update_4.yml
  changelogs/fragments/documentation_update_5.yml
  changelogs/fragments/documentation_update_6.yml
  changelogs/fragments/elb_docs_update.yml
  changelogs/fragments/fix_deperecated_ami.yml
  changelogs/fragments/fix_module_diff_route53.yml
  changelogs/fragments/update_return_block_backup_modules.yml
  changelogs/fragments/update_return_block_cloud_modules.yml
  changelogs/fragments/update_return_block_ec2_2.yml
  changelogs/fragments/update_return_block_lambda.yml
  changelogs/fragments/update_return_block_rds.yml
  changelogs/fragments/update_return_block_route53_health_check.yml
  changelogs/fragments/use_t3a_micro_in_tests.yml
Labels: mergeit

#2275 Add support for AWS RDS Multi-Tenant CDB Databases
  changelogs/fragments/rds_instance_multitenant.yml
  plugins/modules/rds_instance.py
  tests/unit/plugins/modules/test_rds_instance.py
Labels: mergeit, backport-8

#2227 aws_ec2: fix populating SSM inventory for multiple hosts
  changelogs/fragments/2227-fix-ssm-inventory.yml
  plugins/inventory/aws_ec2.py
Labels: mergeit

#2288 s3_bucket - fix typing for Python <3.9
  changelogs/fragments/2287-3_7-compile.yml
  plugins/modules/s3_bucket.py
Labels: mergeit, backport-8

#2291 ec2_vpc_route_table: Add support to configure Transit Gateway routes in route table
  changelogs/fragments/ec2_vpc_rote_table_transit_gateway.yml
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_route_table_info.py
  tests/integration/targets/ec2_vpc_route_table/tasks/main.yml
Labels: mergeit, backport-8

#2297 Fix sanity errors occurring with the devel branch of ansible
  changelogs/fragments/20240919-sanity_fixes_devel.yml
  plugins/modules/ec2_vpc_endpoint.py
  plugins/modules/ec2_vpc_route_table.py
Labels: mergeit

#2301 added module_utils for autoscaling
  changelogs/fragments/20240920-module_utils-autoscaling.yaml
  plugins/module_utils/autoscaling.py
Labels: mergeit

#2304 Create tests/sanity/ignore-2.19.txt
  changelogs/fragments/20240924-create-ignore-2.19.yml
  tests/sanity/ignore-2.19.txt
Labels: mergeit, backport-8

#2292 ec2_eip: add support of updating reverse dns record for eip
  changelogs/fragments/2292-ec2_eip-add-support-to-update-reverse-dns-record.yml
  plugins/modules/ec2_eip.py
  tests/integration/targets/ec2_eip/defaults/main.yml
  tests/integration/targets/ec2_eip/tasks/main.yml
  tests/integration/targets/ec2_eip/tasks/update_reverse_dns_record.yml
  tests/unit/plugins/modules/ec2_eip/test_reverse_dns_record_updates.py
Labels: mergeit

#2298 ec2_instance add the possibility to upgrade/downgrade instance type on the fly
  changelogs/fragments/20240917-ec2_instance-upgrade-downgrade-instance-type.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_instance_multiple/tasks/main.yml
  tests/integration/targets/ec2_instance_type/aliases
  tests/integration/targets/ec2_instance_type/defaults/main.yml
  tests/integration/targets/ec2_instance_type/meta/main.yml
  tests/integration/targets/ec2_instance_type/tasks/main.yml
  tests/integration/targets/ec2_instance_type/tasks/single_instance.yml
  tests/integration/targets/ec2_instance_type/tasks/update_instance_type.yml
  tests/unit/plugins/modules/ec2_instance/test_modify_instance_type.py
Labels: mergeit, backport-8
