Repository ansible-collections/amazon.aws, pull requests merged in 2024-05, with the labels that each got.

#2073 Remove any requirement for botocore < 1.29.0
  changelogs/fragments/20240502-docs_cleanup.yml
  plugins/modules/lambda_info.py
  plugins/modules/rds_cluster.py
Labels: mergeit

#2072 Update return block in documentation for ec2 modules (part 1)
  changelogs/fragments/return_block_update_ec2_1.yml
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_ami_info.py
  plugins/modules/ec2_eip_info.py
  plugins/modules/ec2_eni.py
  plugins/modules/ec2_eni_info.py
  plugins/modules/ec2_instance.py
  plugins/modules/ec2_instance_info.py
  plugins/modules/ec2_security_group.py
  plugins/modules/ec2_security_group_info.py
Labels: mergeit

#2075 Prep amazon.aws 7.6.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240322-s3_object-fix-idempotency-copy-issue-with-multipart-uploaded-object.yml
  changelogs/fragments/20240403-ec2_securty_group-sanity.yml
  changelogs/fragments/20240411-ec2_vol.yml
  changelogs/fragments/2026-ec2_instance-add-support-for-placement-tenancy-host.yml
  changelogs/fragments/2065-iam_role_info.yml
  changelogs/fragments/2067-iam_managed_policy-delete.yml
  changelogs/fragments/cloudformation-template.yml
  changelogs/fragments/sanity-boto3.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2078 [main] 7.6.0 changelog
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240322-s3_object-fix-idempotency-copy-issue-with-multipart-uploaded-object.yml
  changelogs/fragments/20240403-ec2_securty_group-sanity.yml
  changelogs/fragments/2026-ec2_instance-add-support-for-placement-tenancy-host.yml
  changelogs/fragments/2065-iam_role_info.yml
  changelogs/fragments/2067-iam_managed_policy-delete.yml
Labels: mergeit

#2085 Update docs-links for stable-8 branch
  CI.md
  README.md
  changelogs/fragments/20250513-update-docs.yml
  docs/docsite/links.yml
Labels: mergeit, skip-changelog

#2089 RDS Integration tests - Bump MySQL/MariaDB versions to match AWS support
  tests/integration/targets/rds_instance_complex/defaults/main.yml
  tests/integration/targets/rds_instance_modify/defaults/main.yml
  tests/integration/targets/rds_instance_snapshot/defaults/main.yml
  tests/integration/targets/rds_option_group/defaults/main.yml
Labels: mergeit, backport-6, backport-7, backport-8

#2025 lambda_event - add support for maximum_batching_window_in_seconds
  changelogs/fragments/20240325-lambda_event-bugfix.yml
  plugins/modules/lambda_event.py
  tests/integration/targets/lambda_event/tasks/main.yml
  tests/unit/plugins/modules/test_lambda_event.py
Labels: mergeit, backport-8

#2093 Drop support for ansible-core < 2.15
  README.md
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  meta/runtime.yml
Labels: mergeit, skip-changelog, backport-8

#2096 Prep amazon.aws 8.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1829-is_boto3_error-tuple.yml
  changelogs/fragments/1950-elb_application_lb-multiple-listener-certificates-for-alb.yml
  changelogs/fragments/20231127-module_utils-elbv2-update.yaml
  changelogs/fragments/20231211-rds_instance_cloudwatch.yml
  changelogs/fragments/20240208-lambda_event-fix-validate-params.yml
  changelogs/fragments/20240227-zombies.yml
  changelogs/fragments/20240325-lambda_event-bugfix.yml
  changelogs/fragments/20240411-remove-deprecated-sort_json_policy_dict.yml
  changelogs/fragments/20240502-docs_cleanup.yml
  changelogs/fragments/20240516-rds_param_group.yml
  changelogs/fragments/20250513-update-docs.yml
  changelogs/fragments/2057-s3_bucket-refactor.yml
  changelogs/fragments/8.0.0-deprecation-removal.yml
  changelogs/fragments/8.0.0-dev0.yml
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  changelogs/fragments/cloudformation-template.yml
  changelogs/fragments/return_block_update_ec2_1.yml
  changelogs/fragments/sanity-boto3.yml
  changelogs/fragments/sanity-simple.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: test-all-the-targets, skip-changelog

#2101 CONTRIBUTING.md: fix hyperlink
  CONTRIBUTING.md
Labels: mergeit

#2100 Update main branch CHANGELOG after 8.0.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1829-is_boto3_error-tuple.yml
  changelogs/fragments/1950-elb_application_lb-multiple-listener-certificates-for-alb.yml
  changelogs/fragments/20231127-module_utils-elbv2-update.yaml
  changelogs/fragments/20231211-rds_instance_cloudwatch.yml
  changelogs/fragments/20240208-lambda_event-fix-validate-params.yml
  changelogs/fragments/20240227-zombies.yml
  changelogs/fragments/20240325-lambda_event-bugfix.yml
  changelogs/fragments/20240411-remove-deprecated-sort_json_policy_dict.yml
  changelogs/fragments/20240502-docs_cleanup.yml
  changelogs/fragments/20240516-rds_param_group.yml
  changelogs/fragments/2057-s3_bucket-refactor.yml
  changelogs/fragments/8.0.0-deprecation-removal.yml
  changelogs/fragments/8.0.0-dev0.yml
  changelogs/fragments/8.0.0-increase-ansible-core-version.yml
  changelogs/fragments/cloudformation-template.yml
  changelogs/fragments/return_block_update_ec2_1.yml
  changelogs/fragments/sanity-boto3.yml
  changelogs/fragments/sanity-simple.yml
Labels: mergeit

#2079 Update return block of ec2 modules (part 2)
  changelogs/fragments/update_return_block_ec2_2.yml
  plugins/modules/ec2_snapshot.py
  plugins/modules/ec2_snapshot_info.py
  plugins/modules/ec2_spot_instance.py
  plugins/modules/ec2_vol.py
  plugins/modules/ec2_vpc_endpoint.py
  plugins/modules/ec2_vpc_endpoint_info.py
  plugins/modules/ec2_vpc_endpoint_service_info.py
  plugins/modules/ec2_vpc_igw_info.py
  plugins/modules/ec2_vpc_nat_gateway.py
  plugins/modules/ec2_vpc_nat_gateway_info.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_subnet.py
  plugins/modules/ec2_vpc_subnet_info.py
Labels: mergeit

#2108 s3_object - fix MemoryError when downloading large files
  changelogs/fragments/2107-s3_download.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-8

#2080 [Part #1]: Ensures the modules documentation follows the correct formats
  changelogs/fragments/documentation_update.yml
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_group_info.py
  plugins/modules/aws_az_info.py
  plugins/modules/backup_plan.py
  plugins/modules/backup_plan_info.py
  plugins/modules/backup_selection.py
  plugins/modules/backup_tag.py
  plugins/modules/backup_tag_info.py
  plugins/modules/cloudformation.py
  plugins/modules/cloudformation_info.py
  plugins/modules/cloudtrail.py
  plugins/modules/cloudtrail_info.py
  plugins/modules/cloudwatch_metric_alarm.py
  plugins/modules/cloudwatch_metric_alarm_info.py
  plugins/modules/cloudwatchevent_rule.py
  plugins/modules/cloudwatchlogs_log_group.py
  plugins/modules/cloudwatchlogs_log_group_info.py
  plugins/modules/cloudwatchlogs_log_group_metric_filter.py
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_ami_info.py
  plugins/modules/ec2_eip.py
  plugins/modules/ec2_eip_info.py
Labels: mergeit

#2105 backup_vault: remove unnecessary return values from code block
  changelogs/fragments/2105-backup_vault-remove-unnecessary-return-values.yml
  plugins/modules/backup_vault.py
Labels: mergeit

#2082 [Part #3] Ensures the modules documentation follows the correct formats
  changelogs/fragments/documentation_update_3.yml
  plugins/modules/ec2_vol.py
  plugins/modules/ec2_vpc_dhcp_option.py
  plugins/modules/ec2_vpc_endpoint.py
  plugins/modules/ec2_vpc_endpoint_info.py
  plugins/modules/ec2_vpc_igw.py
  plugins/modules/ec2_vpc_igw_info.py
  plugins/modules/ec2_vpc_nat_gateway.py
  plugins/modules/ec2_vpc_nat_gateway_info.py
  plugins/modules/ec2_vpc_net.py
  plugins/modules/ec2_vpc_net_info.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_route_table_info.py
  plugins/modules/ec2_vpc_subnet.py
  plugins/modules/ec2_vpc_subnet_info.py
Labels: mergeit

#1979 Don't ignore IPv6 addresses when a single network interface is specified
  changelogs/fragments/1979-do-not-ignore-ipv6-addresses.yaml
  plugins/modules/ec2_instance.py
Labels: mergeit, backport-7, backport-8

#2111 cloudwatch_metric_alarm: include evaluate_low_sample_count_percentile
  changelogs/fragments/add_evaluate_low_sample_count_percentile.yml
  plugins/modules/cloudwatch_metric_alarm.py
  tests/integration/targets/cloudwatch_metric_alarm/tasks/main.yml
Labels: mergeit

#2115 Update return blocks of cloud* modules
  changelogs/fragments/update_return_block_cloud_modules.yml
  plugins/modules/cloudtrail.py
  plugins/modules/cloudtrail_info.py
  plugins/modules/cloudwatchevent_rule.py
  plugins/modules/cloudwatchlogs_log_group.py
Labels: mergeit
