Repository ansible-collections/amazon.aws, pull requests merged in 2024-01, with the labels that each got.

#1936 iam_managed_policy - add support for path and tagging
  changelogs/fragments/20231222-managed_policy.yml
  plugins/modules/iam_managed_policy.py
  plugins/modules/iam_user.py
  tests/integration/targets/iam_managed_policy/defaults/main.yml
  tests/integration/targets/iam_managed_policy/tasks/main.yml
  tests/integration/targets/iam_managed_policy/tasks/tags.yml
  tests/unit/module_utils/iam/test_validate_iam_identifiers.py
Labels: mergeit, backport-7

#1941 Prepare for release 7.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1918-ec2_instance-add-support-to-modify-metadata-options.yml
  changelogs/fragments/20231206-iam_user_path.yml
  changelogs/fragments/20231219-iam-consistency.yml
  changelogs/fragments/20231222-managed_policy.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#1939 lambda: add support for container image as alternative to runtime
  changelogs/fragments/1939-image_uri.yml
  plugins/modules/lambda.py
  tests/integration/targets/lambda/tasks/main.yml
Labels: mergeit, backport-7

#1944 Pull 7.2.0 changelogs into main branch
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1918-ec2_instance-add-support-to-modify-metadata-options.yml
  changelogs/fragments/20231206-iam_user_path.yml
  changelogs/fragments/20231219-iam-consistency.yml
  changelogs/fragments/20231222-managed_policy.yml
Labels: mergeit, skip-changelog

#1947 Fix version_released for changes that weren't backported in time (7.2.0 -> 7.3.0)
  plugins/modules/rds_cluster.py
  plugins/modules/s3_bucket_info.py
Labels: mergeit, skip-changelog, backport-7

#1950 elb_application_lb: add support for creating alb with listener having multiple certificates
  changelogs/fragments/1950-elb_application_lb-multiple-listener-certificates-for-alb.yml
  plugins/module_utils/elbv2.py
  plugins/modules/elb_application_lb.py
  tests/integration/targets/elb_application_lb/defaults/main.yml
  tests/integration/targets/elb_application_lb/meta/main.yml
  tests/integration/targets/elb_application_lb/tasks/alb_with_multiple_listener_certs.yml
  tests/integration/targets/elb_application_lb/tasks/main.yml
Labels: mergeit

#1957 Bugfix aws_ec2 inventory use_ssm_inventory
  changelogs/fragments/20240129-aws_ec2-inventory-bugfix.yml
  plugins/inventory/aws_ec2.py
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit, backport-6, backport-7

#1951 Add simple decorator for handling common botocore/boto3 errors
  changelogs/fragments/1951-error-handler.yml
  plugins/module_utils/errors.py
  plugins/module_utils/iam.py
  plugins/modules/iam_user.py
  tests/unit/module_utils/errors/aws_error_handler/test_common_handler.py
  tests/unit/module_utils/errors/aws_error_handler/test_deletion_handler.py
  tests/unit/module_utils/errors/aws_error_handler/test_list_handler.py
  tests/unit/module_utils/iam/test_iam_error_handler.py
  tests/unit/module_utils/iam/test_validate_iam_identifiers.py
Labels: mergeit, backport-7
