Repository ansible-collections/amazon.aws, pull requests merged in 2024-03, with the labels that each got.

#2007 Manual backport of PR #1972
  changelogs/fragments/20240212-lookup-secretsmanager_secret-fix-issue-when-nested-is-missing-and-on_missing-is-set-to-warn.yaml
  plugins/lookup/secretsmanager_secret.py
  tests/integration/targets/lookup_secretsmanager_secret/defaults/main.yml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/main.yaml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/nested.yaml
  tests/unit/plugins/lookup/test_secretsmanager_secret.py
Labels: mergeit

#1980 Inventory plugins do not convert template parameters
  plugins/plugin_utils/inventory.py
  tests/integration/targets/inventory_aws_ec2/playbooks/create_inventory_config.yml
  tests/integration/targets/inventory_aws_ec2/templates/config.ini.j2
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_template.yml.j2
  tests/unit/plugin_utils/inventory/test_inventory_base.py
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit

#2013 [Manual backport] Update python runtime version in lambda tests (#1987)
  tests/integration/targets/lambda_alias/tasks/main.yml
  tests/integration/targets/lambda_layer/tasks/main.yml
Labels: mergeit

#2009 Prep amazon.aws 7.4.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1883-cloudwatchevent_rule-fix-json-input-handling-for-input_template.yml
  changelogs/fragments/20240124-module_utils-elbv2-fix-issue-with-authenticated-oidc.yml
  changelogs/fragments/20240212-lookup-secretsmanager_secret-fix-issue-when-nested-is-missing-and-on_missing-is-set-to-warn.yaml
  changelogs/fragments/20240227-fail_aws_error.yml
  changelogs/fragments/20240227-iam-refactor.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2010 Prep amazon.aws 6.5.3
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1883-cloudwatchevent_rule-fix-json-input-handling-for-input_template.yml
  changelogs/fragments/20240212-lookup-secretsmanager_secret-fix-issue-when-nested-is-missing-and-on_missing-is-set-to-warn.yaml
  changelogs/fragments/remove_rendundant_workflow.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2018 s3_object - fix issue when copying object with provided metadata
  changelogs/fragments/20240314-s3_object-copy-mode-with-metadata.yml
  plugins/modules/s3_object.py
  tests/integration/targets/s3_object/aliases
  tests/integration/targets/s3_object/tasks/copy_object.yml
  tests/integration/targets/s3_object/tasks/main.yml
Labels: mergeit, backport-6, backport-7

#2019 cloudwatch_log_groups_info - Fix throttling issue when describing cloudwatch log groups
  changelogs/fragments/20240314-cloudwatchlogs_log_group_info-fix-throttling-exceptions.yml
  plugins/modules/cloudwatchlogs_log_group_info.py
Labels: mergeit, backport-6, backport-7

#2012 returns boolean if a user has access to console login
  changelogs/fragments/20240321-iam-user-info.yml
  plugins/modules/iam_user_info.py
Labels: mergeit, backport-7

#2006 Normalize refactor
  changelogs/fragments/2006-normalize-refactor.yml
  plugins/module_utils/iam.py
  plugins/module_utils/transformation.py
  tests/unit/module_utils/iam/test_iam_resource_transforms.py
  tests/unit/module_utils/transformation/test_boto3_resource_to_ansible_dict.py
Labels: mergeit
