Repository ansible-collections/amazon.aws, pull requests merged in 2025-05, with the labels that each got.

#2602 Skip ansible-core 2.16 for sanity and unit tests
  .github/workflows/sanity.yml
  .github/workflows/units.yml
  changelogs/fragments/skip_ansible-core_2.16.yml
Labels: mergeit, do_not_backport

#2601 Update requires_ansible version
  README.md
  changelogs/fragments/10.0.0-increase-ansible-core-version.yml
  meta/runtime.yml
Labels: mergeit, do_not_backport

#2608 Integration test fixes
  tests/integration/targets/backup_plan/tasks/main.yml
  tests/integration/targets/ec2_vpc_dhcp_option/tasks/main.yml
  tests/integration/targets/ec2_vpc_egress_igw/tasks/main.yml
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_hostnames_with_jinja2_filters.yml.j2
  tests/integration/targets/rds_instance_tagging/tasks/main.yml
  tests/integration/targets/rds_instance_tagging/tasks/test_tagging_gp3.yml
  tests/integration/targets/s3_object/tasks/copy_multipart_upload.yml
  tests/integration/targets/s3_object/tasks/main.yml
Labels: mergeit, skip-changelog, backport-9

#2603 Remove boto3 deprecated parameter
  changelogs/fragments/boto3-cleanup.yml
  plugins/module_utils/ec2.py
  plugins/module_utils/modules.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostnames_with_jinja2_filters.yml
Labels: mergeit, do_not_backport

#2607 module_utils/modules.py - Fix sanity error with devel
  changelogs/fragments/20250506-module_utils-modules-fix-sanity-with-devel.yml
  plugins/module_utils/modules.py
Labels: mergeit, backport-9

#2613 stable-9: manual backport of Integration test fixes (#2608)
  tests/integration/targets/backup_plan/tasks/main.yml
  tests/integration/targets/ec2_vpc_dhcp_option/tasks/main.yml
  tests/integration/targets/ec2_vpc_egress_igw/tasks/main.yml
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_hostnames_with_jinja2_filters.yml.j2
  tests/integration/targets/rds_instance_tagging/tasks/main.yml
  tests/integration/targets/rds_instance_tagging/tasks/test_tagging_gp3.yml
  tests/integration/targets/s3_object/tasks/copy_multipart_upload.yml
  tests/integration/targets/s3_object/tasks/main.yml
Labels: mergeit

#2617 Update links for stable-10 branch
  CI.md
  README.md
  changelogs/fragments/20250508-update-docs.yml
  docs/docsite/links.yml
Labels: mergeit

#2618 Remove deprecated rds_param_group redirect
  changelogs/fragments/2618-remove-rds-param-group.yml
  galaxy.yml
  meta/runtime.yml
  plugins/module_utils/common.py
  plugins/modules/ec2_vpc_peering_info.py
  plugins/modules/rds_cluster_param_group.py
  tests/integration/targets/ec2_vpc_peering/tasks/main.yml
Labels: mergeit, do_not_backport

#2614 stable-9: manual backport - module_utils/modules.py - call to deprecate should specified argument…
  changelogs/fragments/20250506-module_utils-modules-fix-sanity-with-devel.yml
  plugins/module_utils/modules.py
  tests/integration/targets/ec2_vpc_nacl/tasks/ipv6.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/public_access.yml
Labels: mergeit

#2599 Prep amazon.aws 9.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20250506-module_utils-modules-fix-sanity-with-devel.yml
  changelogs/fragments/2567-iam-user-info-add-missing-tags.yml
  changelogs/fragments/2567-iam-user-info-fix-get-user-condition.yml
  changelogs/fragments/2567-iam-user-info-fix-path-prefix-condition.yml
  changelogs/fragments/2567-iam-user-info-handle-non-existant-group.yml
  changelogs/fragments/2582-cancel-autoscaling-instance-refresh-error-message.yml
  changelogs/fragments/2594-route53_info_docs.yml
  changelogs/fragments/update_ansible-lint.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2620 Update main branch after release 9.5.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20250506-module_utils-modules-fix-sanity-with-devel.yml
  changelogs/fragments/2567-iam-user-info-add-missing-tags.yml
  changelogs/fragments/2567-iam-user-info-fix-get-user-condition.yml
  changelogs/fragments/2567-iam-user-info-fix-path-prefix-condition.yml
  changelogs/fragments/2567-iam-user-info-handle-non-existant-group.yml
  changelogs/fragments/2582-cancel-autoscaling-instance-refresh-error-message.yml
  changelogs/fragments/2594-route53_info_docs.yml
  changelogs/fragments/update_ansible-lint.yml
Labels: mergeit, skip-changelog, backport-10

#2623 fix integration tests broken conditionals
  tests/integration/targets/lookup_aws_service_ip_ranges/tasks/main.yaml
  tests/integration/targets/module_utils_botocore_recorder/main.yml
  tests/integration/targets/s3_object_info_prefix/tasks/main.yml
Labels: mergeit, skip-changelog, backport-9, backport-10

#2627 Fix data tagging issues in lookup plugin integration tests
  tests/integration/targets/lookup_secretsmanager_secret/defaults/main.yml
  tests/integration/targets/lookup_secretsmanager_secret/tasks/nested.yaml
  tests/integration/targets/lookup_ssm_parameter/tasks/main.yml
Labels: mergeit, skip-changelog, backport-9, backport-10

#2622 Prep amazon.aws 10.0.0
  CHANGELOG.rst
  CI.md
  changelogs/changelog.yaml
  changelogs/fragments/10.0.0-increase-ansible-core-version.yml
  changelogs/fragments/20241029-main-10.0.0.yml
  changelogs/fragments/20250117-s3_bucket-error_handler.yml
  changelogs/fragments/20250508-update-docs.yml
  changelogs/fragments/2060-s3_error_handler.yml
  changelogs/fragments/2443-boto-final-clean.yml
  changelogs/fragments/2527-module_aliases.yml
  changelogs/fragments/2618-remove-rds-param-group.yml
  changelogs/fragments/boto3-cleanup.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/migrate_aws_ssm.yml
  changelogs/fragments/s3_bucket-501.yml
  changelogs/fragments/skip_ansible-core_2.16.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2632 Update main branch after release 10.0.0
  CHANGELOG.rst
  CI.md
  changelogs/changelog.yaml
  changelogs/fragments/10.0.0-increase-ansible-core-version.yml
  changelogs/fragments/20241029-main-10.0.0.yml
  changelogs/fragments/20250117-s3_bucket-error_handler.yml
  changelogs/fragments/2060-s3_error_handler.yml
  changelogs/fragments/2443-boto-final-clean.yml
  changelogs/fragments/2527-module_aliases.yml
  changelogs/fragments/2618-remove-rds-param-group.yml
  changelogs/fragments/boto3-cleanup.yml
  changelogs/fragments/botocore.yml
  changelogs/fragments/migrate_aws_ssm.yml
  changelogs/fragments/s3_bucket-501.yml
  changelogs/fragments/skip_ansible-core_2.16.yml
Labels: mergeit, skip-changelog, backport-10
