Repository ansible-collections/amazon.aws, pull requests merged in 2025-03, with the labels that each got.

#2539 Prep amazon.aws 9.3.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2529-s3_object-create-metadata.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2540 Update main branch after amazon.aws 9.3.0 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/2529-s3_object-create-metadata.yml
Labels: mergeit, backport-9

#2544 ansible-core 2.19 - Fix tests with data tagging
  tests/integration/targets/ec2_ami_instance/tasks/main.yml
  tests/integration/targets/ec2_instance_termination_protection/tasks/main.yml
  tests/integration/targets/ec2_security_group/tasks/main.yml
  tests/integration/targets/ec2_vpc_subnet/tasks/main.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/default_retention.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_bucket_key.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_kms.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_sse.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/inventory.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/ownership_controls.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/public_access.yml
  tests/integration/targets/s3_bucket_info/tasks/basic.yml
Labels: mergeit, backport-9

#2549 Update tests for ansible 2.19
  tests/integration/targets/ec2_vpc_igw/tasks/main.yml
  tests/integration/targets/ec2_vpc_net/tasks/main.yml
  tests/integration/targets/ec2_vpc_route_table/tasks/main.yml
Labels: mergeit, backport-9

#2554 Update tests for ansible 2.19
  tests/integration/targets/autoscaling_group/roles/ec2_asg/tasks/main.yml
  tests/integration/targets/ec2_launch_template/tasks/deletion.yml
  tests/integration/targets/ec2_vpc_vpn/tasks/main.yml
Labels: mergeit, backport-9

#2552 ansible 2.19 data tagging testing
  changelogs/fragments/20250319-ansible-core-2-19-testing.yaml
  plugins/inventory/aws_ec2.py
  plugins/lookup/aws_account_attribute.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostnames_with_jinja2_filters.yml
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_hostnames_with_jinja2_filters.yml.j2
  tests/integration/targets/lookup_aws_account_attribute/tasks/main.yaml
  tests/integration/targets/route53_health_check/aliases
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit, backport-9

#2559 Part 8 - 2.19 data tagging
  tests/integration/targets/ec2_vpc_nacl/tasks/ipv6.yml
Labels: mergeit

#2558 Part 6 - 2.19 data tagging
  plugins/modules/elb_classic_lb.py
  tests/integration/targets/cloudwatchevent_rule/tasks/test_json_input_template.yml
  tests/integration/targets/rds_cluster_param_group/tasks/main.yaml
Labels: mergeit, skip-changelog, backport-9

#2567 Fix iam user info issues
  changelogs/fragments/2567-iam-user-info-add-missing-tags.yml
  changelogs/fragments/2567-iam-user-info-fix-get-user-condition.yml
  changelogs/fragments/2567-iam-user-info-fix-path-prefix-condition.yml
  changelogs/fragments/2567-iam-user-info-handle-non-existant-group.yml
  plugins/module_utils/iam.py
  plugins/modules/iam_user_info.py
  tests/integration/targets/iam_user/tasks/path.yml
  tests/integration/targets/iam_user/tasks/search_group.yml
  tests/integration/targets/iam_user/tasks/tags.yml
Labels: mergeit, backport-8, backport-9
