Repository ansible-collections/amazon.aws, pull requests merged in 2025-01, with the labels that each got.

#2430 route53: add support for type SSHFP
  changelogs/fragments/2430-route53-sshfp-record-type-support.yml
  plugins/modules/route53.py
Labels: mergeit, backport-9

#2448 Manual partial backport of PR 2397 to stable-8 - Fix integration tests for EC2 inventory
  tests/integration/targets/inventory_aws_ec2/meta/main.yml
  tests/integration/targets/inventory_aws_ec2/playbooks/tasks
  tests/integration/targets/inventory_aws_ec2/playbooks/test_inventory_ssm.yml
  tests/integration/targets/inventory_aws_ec2/runme.sh
  tests/integration/targets/inventory_aws_ec2/tasks/setup.yml
  tests/integration/targets/setup_ec2_facts/defaults/main.yml
Labels: mergeit

#2427 inventory/aws_ec2 - support jinja2 filters in hostnames option
  changelogs/fragments/20241217-inventory-aws_ec2-support-jinja2-in-hostnames-variables.yaml
  plugins/inventory/aws_ec2.py
  tests/integration/targets/inventory_aws_ec2/playbooks/test_populating_inventory_with_hostnames_with_jinja2_filters.yml
  tests/integration/targets/inventory_aws_ec2/runme.sh
  tests/integration/targets/inventory_aws_ec2/templates/inventory_with_hostnames_with_jinja2_filters.yml.j2
Labels: mergeit, backport-8, backport-9

#2449 Prep amazon.aws 9.1.1 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241127-rds_cluster-fix-issue-occurring-when-updating-domain.yml
  changelogs/fragments/20241129-ec2_security_group-fix-issue-with-with-mode.yaml
  changelogs/fragments/20241206-ec2_nat_gateway-retry-on-invalid-elastic-ip-id.yaml
  changelogs/fragments/2386-lambda-remove-non-utf-8-output.yml
  changelogs/fragments/2391-cloudformation-update-stack-termination_protection.yml
  changelogs/fragments/handle_vpc_ipv6_false.yml
  changelogs/fragments/tests-fqcn.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2443 Remove deprecated boto3 parameter
  changelogs/fragments/2443-boto-final-clean.yml
  plugins/module_utils/botocore.py
Labels: mergeit, do_not_backport

#2454 Add a workflow which automatically adds backport tags based upon changelogs
  .github/workflows/backports.yml
  docs/docsite/rst/collection_release.rst
Labels: mergeit, do_not_backport, skip-changelog

#2457 s3_bucket - do not use the default region as location constraint (ceph)
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  plugins/module_utils/s3.py
  plugins/modules/s3_bucket.py
Labels: mergeit, backport-8, backport-9

#2453 Update version_added for some module options
  changelogs/fragments/20250110-documentation-block-updates.yml
  plugins/modules/cloudwatchlogs_log_group_metric_filter.py
  plugins/modules/ec2_eip.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_route_table_info.py
Labels: mergeit, backport-9

#2461 Use pull_request_target for backport workflow
  .github/workflows/backports.yml
Labels: mergeit, skip-changelog

#2458 Sync changes from 9.1.1 release (#2449)
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241127-rds_cluster-fix-issue-occurring-when-updating-domain.yml
  changelogs/fragments/20241129-ec2_security_group-fix-issue-with-with-mode.yaml
  changelogs/fragments/20241206-ec2_nat_gateway-retry-on-invalid-elastic-ip-id.yaml
  changelogs/fragments/2386-lambda-remove-non-utf-8-output.yml
  changelogs/fragments/2391-cloudformation-update-stack-termination_protection.yml
  changelogs/fragments/handle_vpc_ipv6_false.yml
  changelogs/fragments/tests-fqcn.yml
Labels: mergeit, do_not_backport, skip-changelog

#2429 ec2_vpc_nacl_info - Fix failure when listing NetworkACLs (#2425)
  changelogs/fragments/20241219-ec2_vpc_nacl_info-fix-issue-returning-results.yml
  plugins/modules/ec2_vpc_nacl_info.py
  tests/integration/targets/ec2_vpc_nacl/tasks/main.yml
Labels: mergeit, backport-8, backport-9

#2462 Revert stable 8 backports
  changelogs/fragments/20240906-cloudwatch-log-metric-filter-unit-dimensions.yml
  changelogs/fragments/20250114-revert-backports.yml
  changelogs/fragments/ec2_vpc_rote_table_transit_gateway.yml
  plugins/modules/cloudwatchlogs_log_group_metric_filter.py
  plugins/modules/ec2_vpc_route_table.py
  plugins/modules/ec2_vpc_route_table_info.py
  tests/integration/targets/cloudwatchlogs/tasks/cloudwatchlogs_tests.yml
  tests/integration/targets/ec2_vpc_route_table/tasks/main.yml
Labels: mergeit

#2452 Prep 8.2.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/202401025-ec2_vol.yml
  changelogs/fragments/20240919-sanity_fixes_devel.yml
  changelogs/fragments/20240924-create-ignore-2.19.yml
  changelogs/fragments/20241106-fqcn-cloudwatch-metric-alarm.yml
  changelogs/fragments/20241127-rds_cluster-fix-issue-occurring-when-updating-domain.yml
  changelogs/fragments/20241129-ec2_security_group-fix-issue-with-with-mode.yaml
  changelogs/fragments/20250114-revert-backports.yml
  changelogs/fragments/2227-fix-ssm-inventory.yml
  changelogs/fragments/2287-3_7-compile.yml
  changelogs/fragments/2386-lambda-remove-non-utf-8-output.yml
  changelogs/fragments/2391-cloudformation-update-stack-termination_protection.yml
  changelogs/fragments/handle_vpc_ipv6_false.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2412 route53_key_signing_key - new module
  meta/runtime.yml
  plugins/modules/route53_key_signing_key.py
  tests/integration/targets/route53_key_signing_key/aliases
  tests/integration/targets/route53_key_signing_key/tasks/main.yml
  tests/integration/targets/route53_key_signing_key/templates/kms_policy.j2
Labels: mergeit, skip-changelog

#2468 Sync changes from 8.2.2 release
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, backport-9

#2349 Update docs
  plugins/callback/aws_resource_actions.py
  plugins/inventory/aws_ec2.py
  plugins/inventory/aws_rds.py
  plugins/lookup/aws_account_attribute.py
  plugins/lookup/aws_collection_constants.py
  plugins/lookup/aws_service_ip_ranges.py
  plugins/lookup/secretsmanager_secret.py
  plugins/lookup/ssm_parameter.py
Labels: mergeit, skip-changelog, backport-9

#2470 [Manual backport] route53_key_signing_key - new module (#2412)
  meta/runtime.yml
  plugins/modules/route53_key_signing_key.py
  tests/integration/targets/route53_key_signing_key/aliases
  tests/integration/targets/route53_key_signing_key/tasks/main.yml
  tests/integration/targets/route53_key_signing_key/templates/kms_policy.j2
Labels: mergeit, skip-changelog

#2421 route53_zone - Add support for enabling DNSSEC signing in a specific hosted zone
  changelogs/fragments/20241203-route53-dnssec.yml
  plugins/modules/route53_zone.py
  tests/integration/targets/route53_key_signing_key/tasks/main.yml
Labels: mergeit, backport-9

#2060 S3ErrorHandler
  changelogs/fragments/2060-s3_error_handler.yml
  plugins/module_utils/s3.py
  tests/unit/module_utils/s3/test_endpoints.py
  tests/unit/module_utils/s3/test_etags.py
  tests/unit/module_utils/s3/test_s3_error_handler.py
  tests/unit/module_utils/s3/test_validate_bucket_name.py
Labels: mergeit, do_not_backport

#2472 Add Github worflow that adds backport_failed label when automatic backports fail
  .github/workflows/check_backports.yml
Labels: mergeit, do_not_backport, skip-changelog

#2476 Fix .github/workflows/backports-check.yml workflow
  .github/workflows/backports-check.yml
Labels: mergeit, backport-9

#2482 Fixup patchback failure labelling
  .github/workflows/backports-check.yml
Labels: mergeit, backport-9

#2483 Patchback checker debug
  .github/workflows/backports-check.yml
Labels: mergeit, backport-9

#2484 fixup patchback username in workflow
  .github/workflows/backports-check.yml
Labels: mergeit, backport-9

#2485 s3_object_info - add support for prefix when listing objects
  changelogs/fragments/20250123-s3_object_info-add-support-to-list-objects-under-a-specific-prefix.yml
  plugins/modules/s3_object_info.py
  tests/integration/targets/s3_object_info_prefix/aliases
  tests/integration/targets/s3_object_info_prefix/tasks/main.yml
Labels: mergeit, backport-9

#2478 Rework s3_bucket to use ErrorHandler model
  changelogs/fragments/20250117-s3_bucket-error_handler.yml
  plugins/module_utils/_s3/common.py
  plugins/module_utils/_s3/transformations.py
  plugins/module_utils/_s3/waiters.py
  plugins/module_utils/s3.py
  plugins/modules/s3_bucket.py
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/acl.yml
  tests/integration/targets/s3_bucket/roles/s3_bucket/tasks/encryption_bucket_key.yml
  tests/unit/plugins/module_utils/s3/test_s3_acl_to_name.py
  tests/unit/plugins/modules/s3_bucket/test_handle_bucket_accelerate.py
Labels: mergeit, do_not_backport

#2488 ec2_instance: Use "vpc_subnet_id" from module.params when subnet_id is missing from network interface
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_security_group/defaults/main.yml
  tests/integration/targets/ec2_instance_security_group/tasks/main.yml
  tests/integration/targets/ec2_instance_security_group/tasks/test_default_sec_group.yml
Labels: mergeit, backport-8, backport-9

#2490 [Manual backport] Backport pr-2488 to stable-8
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
  plugins/modules/ec2_instance.py
  tests/integration/targets/ec2_instance_security_group/defaults/main.yml
  tests/integration/targets/ec2_instance_security_group/tasks/main.yml
  tests/integration/targets/ec2_instance_security_group/tasks/test_default_sec_group.yml
Labels: mergeit
