Repository ansible-collections/amazon.aws, pull requests merged in 2025-02, with the labels that each got.

#2495 [Manual Backport] Add ruff to tox.ini and fix some minor linting issues
  changelogs/fragments/20250114-ruff.yml
  plugins/module_utils/errors.py
  plugins/module_utils/iam.py
  plugins/module_utils/s3.py
  plugins/modules/autoscaling_group.py
  plugins/modules/autoscaling_instance.py
  plugins/modules/ec2_security_group.py
  plugins/modules/ec2_transit_gateway.py
  plugins/modules/ec2_vpc_egress_igw.py
  plugins/modules/ec2_vpc_nacl.py
  plugins/modules/elb_classic_lb.py
  plugins/modules/iam_password_policy.py
  plugins/modules/iam_role.py
  plugins/modules/kms_key.py
  plugins/modules/lambda.py
  plugins/modules/route53_health_check.py
  plugins/modules/route53_zone.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_object.py
  plugins/modules/s3_object_info.py
  pyproject.toml
  tests/integration/targets/ec2_vpc_nacl/tasks/main.yml
  tests/integration/targets/setup_sshkey/files/ec2-fingerprint.py
  tests/unit/module_utils/botocore/test_aws_region.py
  tests/unit/module_utils/retries/test_retry_wrapper.py
  tests/unit/module_utils/test_get_aws_account_id.py
  tests/unit/plugin_utils/connection/test_connection_base.py
  tests/unit/plugins/modules/test_ec2_ami.py
  tests/unit/plugins/modules/test_ec2_key.py
  tests/unit/plugins/modules/test_kms_key.py
  tests/unit/utils/amazon_placebo_fixtures.py
  tox.ini
Labels: mergeit

#2496 Fix assertion way to check the AZ group_name attribute
  changelogs/fragments/20250202-assertion-group-name-aws-az-info.yml
  tests/integration/targets/aws_az_info/tasks/main.yml
Labels: mergeit, backport-8, backport-9

#2497 Minor typing fixups
  changelogs/fragments/20250202-typealias.yml
  plugins/module_utils/_s3/common.py
  plugins/module_utils/botocore.py
  plugins/module_utils/exceptions.py
  plugins/plugin_utils/botocore.py
Labels: mergeit, backport-9

#2493 [Manual Backport] Various pylint fixups (#2444)
  changelogs/fragments/2444-pylint.yml
  plugins/modules/ec2_ami.py
  plugins/modules/ec2_vpc_vpn.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_object.py
  tests/integration/targets/s3_object/library/test_s3_upload_multipart.py
  tests/unit/conftest.py
  tests/unit/module_utils/botocore/test_aws_region.py
  tests/unit/module_utils/botocore/test_boto3_conn.py
  tests/unit/module_utils/botocore/test_connection_info.py
  tests/unit/module_utils/botocore/test_merge_botocore_config.py
  tests/unit/module_utils/cloud/test_decorator_generation.py
  tests/unit/module_utils/cloud/test_retry_func.py
  tests/unit/module_utils/conftest.py
  tests/unit/module_utils/ec2/test_determine_iam_role.py
  tests/unit/module_utils/elbv2/test_listener_rules.py
  tests/unit/module_utils/exceptions/test_exceptions.py
  tests/unit/module_utils/retries/test_retry_wrapper.py
  tests/unit/module_utils/test_acm.py
  tests/unit/module_utils/test_cloudfront_facts.py
  tests/unit/module_utils/test_rds.py
  tests/unit/plugin_utils/botocore/test_boto3_conn_plugin.py
  tests/unit/plugin_utils/botocore/test_get_aws_region.py
  tests/unit/plugin_utils/botocore/test_get_connection_info.py
  tests/unit/plugin_utils/inventory/test_inventory_base.py
  tests/unit/plugins/inventory/test_aws_ec2.py
  tests/unit/plugins/inventory/test_aws_rds.py
  tests/unit/plugins/lookup/test_secretsmanager_secret.py
  tests/unit/plugins/modules/ec2_eip/test_check_is_instance.py
  tests/unit/plugins/modules/ec2_eip/test_generate_tag_dict.py
  tests/unit/plugins/modules/ec2_eip/test_reverse_dns_record_updates.py
  tests/unit/plugins/modules/ec2_instance/test_build_run_instance_spec.py
  tests/unit/plugins/modules/ec2_instance/test_modify_instance_type.py
  tests/unit/plugins/modules/ec2_security_group/test_get_target_from_rule.py
  tests/unit/plugins/modules/ec2_security_group/test_validate_ip.py
  tests/unit/plugins/modules/s3_bucket/test_handle_bucket_accelerate.py
  tests/unit/plugins/modules/test_backup_restore_job_info.py
  tests/unit/plugins/modules/test_cloudformation.py
  tests/unit/plugins/modules/test_ec2_ami_info.py
  tests/unit/plugins/modules/test_ec2_eni_info.py
  tests/unit/plugins/modules/test_ec2_import_image.py
  tests/unit/plugins/modules/test_ec2_metadata_facts.py
  tests/unit/plugins/modules/test_ec2_vpc_dhcp_option.py
  tests/unit/plugins/modules/test_ec2_vpc_net.py
  tests/unit/plugins/modules/test_lambda_event.py
  tests/unit/plugins/modules/test_rds_cluster.py
  tests/unit/utils/amazon_placebo_fixtures.py
Labels: mergeit

#2502 [Manual Backport][Stable-8] s3_bucket - do not use default region as location constraint when creating bucket on ceph cluster
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  plugins/module_utils/s3.py
  plugins/modules/s3_bucket.py
Labels: mergeit

#2501 [Backport][Stable-9]Minor typing fixups (#2497)
  changelogs/fragments/20250202-typealias.yml
  plugins/module_utils/_s3/common.py
  plugins/module_utils/botocore.py
  plugins/module_utils/exceptions.py
  plugins/plugin_utils/botocore.py
Labels: mergeit

#2505 [Manual Backport][Stable-8] Update Readme to match the template (#2200)
  README.md
  changelogs/fragments/readme_template_update.yml
Labels: mergeit

#2509 s3_object - use copy rather than copy_object
  changelogs/fragments/2117-s3_object-copy.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-9

#2379 Add filters to list of templatable inventory options.
  changelogs/fragments/20241129-fix_filter.yml
  plugins/plugin_utils/inventory.py
Labels: mergeit, backport-9

#2513 Revert "Prep amazon.aws 9.2.0 release"
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241203-route53-dnssec.yml
  changelogs/fragments/20241217-inventory-aws_ec2-support-jinja2-in-hostnames-variables.yaml
  changelogs/fragments/20241219-ec2_vpc_nacl_info-fix-issue-returning-results.yml
  changelogs/fragments/20250110-documentation-block-updates.yml
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  changelogs/fragments/20250114-iam_access_key.yml
  changelogs/fragments/20250114-ruff.yml
  changelogs/fragments/20250123-s3_object_info-add-support-to-list-objects-under-a-specific-prefix.yml
  changelogs/fragments/20250202-assertion-group-name-aws-az-info.yml
  changelogs/fragments/20250202-typealias.yml
  changelogs/fragments/2117-s3_object-copy.yml
  changelogs/fragments/2430-route53-sshfp-record-type-support.yml
  changelogs/fragments/2444-pylint.yml
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit

#2515 Release prep 9.2.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241129-fix_filter.yml
  changelogs/fragments/20241203-route53-dnssec.yml
  changelogs/fragments/20241217-inventory-aws_ec2-support-jinja2-in-hostnames-variables.yaml
  changelogs/fragments/20241219-ec2_vpc_nacl_info-fix-issue-returning-results.yml
  changelogs/fragments/20250110-documentation-block-updates.yml
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  changelogs/fragments/20250114-iam_access_key.yml
  changelogs/fragments/20250114-ruff.yml
  changelogs/fragments/20250123-s3_object_info-add-support-to-list-objects-under-a-specific-prefix.yml
  changelogs/fragments/20250202-assertion-group-name-aws-az-info.yml
  changelogs/fragments/20250202-typealias.yml
  changelogs/fragments/2117-s3_object-copy.yml
  changelogs/fragments/2430-route53-sshfp-record-type-support.yml
  changelogs/fragments/2444-pylint.yml
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2514 Prep amazon.aws 8.2.3 release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  changelogs/fragments/20250202-assertion-group-name-aws-az-info.yml
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
  changelogs/fragments/readme_template_update.yml
  galaxy.yml
  plugins/module_utils/common.py
Labels: mergeit, skip-changelog

#2518 Sync changes from 9.2.0 to main
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20241129-fix_filter.yml
  changelogs/fragments/20241203-route53-dnssec.yml
  changelogs/fragments/20241217-inventory-aws_ec2-support-jinja2-in-hostnames-variables.yaml
  changelogs/fragments/20241219-ec2_vpc_nacl_info-fix-issue-returning-results.yml
  changelogs/fragments/20250110-documentation-block-updates.yml
  changelogs/fragments/20250113-s3_bucket-location-constraints-for-ceph-cluster.yml
  changelogs/fragments/20250114-iam_access_key.yml
  changelogs/fragments/20250114-ruff.yml
  changelogs/fragments/20250123-s3_object_info-add-support-to-list-objects-under-a-specific-prefix.yml
  changelogs/fragments/20250202-assertion-group-name-aws-az-info.yml
  changelogs/fragments/20250202-typealias.yml
  changelogs/fragments/2117-s3_object-copy.yml
  changelogs/fragments/2430-route53-sshfp-record-type-support.yml
  changelogs/fragments/2444-pylint.yml
  changelogs/fragments/2488-ec2_instance-fix-security-group-attachment-issue.yml
Labels: mergeit, backport-9

#2508 module_utils.s3 - added 501 to the list of tolerated 'NotImplemented' error codes
  changelogs/fragments/s3_bucket-501.yml
  plugins/module_utils/_s3/common.py
Labels: mergeit, do_not_backport

#2520 update upload-artifact and download-artifact to v4
  .github/actions/ansible_release_log/action.yml
  .github/actions/ansible_release_tag/action.yml
Labels: mergeit, backport-9

#2517 s3_bucket - cleanup typing
  plugins/module_utils/botocore.py
  plugins/modules/s3_bucket.py
Labels: mergeit, do_not_backport, skip-changelog

#2529 Enable metadata folder settings in create mode
  changelogs/fragments/2529-s3_object-create-metadata.yml
  plugins/modules/s3_object.py
Labels: mergeit, backport-9

#2527 Remove deprecated common parameter aliases
  changelogs/fragments/2527-module_aliases.yml
  plugins/doc_fragments/aws.py
  plugins/doc_fragments/aws_credentials.py
  plugins/doc_fragments/aws_region.py
  plugins/doc_fragments/common.py
  plugins/doc_fragments/ec2.py
  plugins/doc_fragments/region.py
  plugins/module_utils/modules.py
  plugins/modules/s3_bucket.py
  plugins/modules/s3_object.py
  plugins/modules/s3_object_info.py
  tests/integration/targets/module_utils_core/roles/ansibleawsmodule.client/tasks/ca_bundle.yml
  tests/integration/targets/module_utils_core/roles/ansibleawsmodule.client/tasks/credentials.yml
  tests/integration/targets/module_utils_core/roles/ansibleawsmodule.client/tasks/endpoints.yml
  tests/integration/targets/module_utils_core/roles/ansibleawsmodule.client/tasks/profiles.yml
  tests/integration/targets/rds_param_group/tasks/main.yml
  tests/unit/plugins/inventory/test_aws_ec2.py
Labels: mergeit, do_not_backport

#2522 Add ec2_dedicated_host and ec2_dedicated_host_info modules
  meta/runtime.yml
  plugins/module_utils/ec2.py
  plugins/modules/ec2_dedicated_host.py
  plugins/modules/ec2_dedicated_host_info.py
  tests/unit/plugins/modules/test_ec2_dedicated_host.py
Labels: mergeit, skip-changelog, backport-9
