Repository ansible-collections/amazon.aws, pull requests merged in 2025-08, with the labels that each got.

#2687 Update mariadb engine version in the tests
  .ansible-lint
  tests/integration/targets/rds_instance_complex/defaults/main.yml
  tests/integration/targets/rds_instance_modify/defaults/main.yml
  tests/integration/targets/rds_instance_snapshot/defaults/main.yml
  tests/integration/targets/rds_instance_upgrade/defaults/main.yml
  tests/sanity/ignore-2.20.txt
Labels: mergeit, skip-changelog, backport-10

#2696 Sync to main after the release of v10.1.1
  CHANGELOG.rst
  changelogs/changelog.yaml
Labels: mergeit, do_not_backport, skip-changelog

#2697 Fix bullet list format in README.md
  README.md
Labels: mergeit, skip-changelog, backport-9, backport-10

#2710 Autoscaling instance refresh test fix
  tests/integration/targets/autoscaling_instance_refresh/tasks/start_cancel_instance_refresh.yml
Labels: mergeit, backport-10
